/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AAPConfig
 */
export interface AAPConfig {
    /**
     * Path to AAP license manifest.zip on the Landing Zone
     * @type {string}
     * @memberof AAPConfig
     */
    aapLicenseFile: string;
    /**
     * Disable the Automation Controller component
     * @type {boolean}
     * @memberof AAPConfig
     */
    aapControllerDisabled?: boolean;
    /**
     * Disable the Event-Driven Ansible component
     * @type {boolean}
     * @memberof AAPConfig
     */
    aapEdaDisabled?: boolean;
    /**
     * Disable the Automation Hub component
     * @type {boolean}
     * @memberof AAPConfig
     */
    aapHubDisabled?: boolean;
    /**
     * Image pull policy for AAP pods
     * @type {string}
     * @memberof AAPConfig
     */
    aapImagePullPolicy?: AAPConfigAapImagePullPolicyEnum;
    /**
     * Name of the Kubernetes secret holding the AAP license
     * @type {string}
     * @memberof AAPConfig
     */
    aapLicenseSecret?: string;
    /**
     * Disable the Ansible Lightspeed component
     * @type {boolean}
     * @memberof AAPConfig
     */
    aapLightspeedDisabled?: boolean;
    /**
     * Name of the AAP instance
     * @type {string}
     * @memberof AAPConfig
     */
    aapName?: string;
    /**
     * Suppress sensitive log output
     * @type {boolean}
     * @memberof AAPConfig
     */
    aapNoLog?: boolean;
    /**
     * Namespace for the AAP deployment
     * @type {string}
     * @memberof AAPConfig
     */
    aapNs?: string;
    /**
     * Redis deployment mode
     * @type {string}
     * @memberof AAPConfig
     */
    aapRedisMode?: AAPConfigAapRedisModeEnum;
    /**
     * TLS termination type for AAP routes
     * @type {string}
     * @memberof AAPConfig
     */
    aapRouteTlsTermination?: AAPConfigAapRouteTlsTerminationEnum;
}


/**
 * @export
 */
export const AAPConfigAapImagePullPolicyEnum = {
    Always: 'Always',
    IfNotPresent: 'IfNotPresent',
    Never: 'Never'
} as const;
export type AAPConfigAapImagePullPolicyEnum = typeof AAPConfigAapImagePullPolicyEnum[keyof typeof AAPConfigAapImagePullPolicyEnum];

/**
 * @export
 */
export const AAPConfigAapRedisModeEnum = {
    Standalone: 'standalone',
    Cluster: 'cluster'
} as const;
export type AAPConfigAapRedisModeEnum = typeof AAPConfigAapRedisModeEnum[keyof typeof AAPConfigAapRedisModeEnum];

/**
 * @export
 */
export const AAPConfigAapRouteTlsTerminationEnum = {
    Edge: 'Edge',
    Passthrough: 'Passthrough',
    Reencrypt: 'Reencrypt'
} as const;
export type AAPConfigAapRouteTlsTerminationEnum = typeof AAPConfigAapRouteTlsTerminationEnum[keyof typeof AAPConfigAapRouteTlsTerminationEnum];


/**
 * Check if a given object implements the AAPConfig interface.
 */
export function instanceOfAAPConfig(value: object): value is AAPConfig {
    if (!('aapLicenseFile' in value) || value['aapLicenseFile'] === undefined) return false;
    return true;
}

export function AAPConfigFromJSON(json: any): AAPConfig {
    return AAPConfigFromJSONTyped(json, false);
}

export function AAPConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AAPConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'aapLicenseFile': json['aapLicenseFile'],
        'aapControllerDisabled': json['aap_controller_disabled'] == null ? undefined : json['aap_controller_disabled'],
        'aapEdaDisabled': json['aap_eda_disabled'] == null ? undefined : json['aap_eda_disabled'],
        'aapHubDisabled': json['aap_hub_disabled'] == null ? undefined : json['aap_hub_disabled'],
        'aapImagePullPolicy': json['aap_image_pull_policy'] == null ? undefined : json['aap_image_pull_policy'],
        'aapLicenseSecret': json['aap_license_secret'] == null ? undefined : json['aap_license_secret'],
        'aapLightspeedDisabled': json['aap_lightspeed_disabled'] == null ? undefined : json['aap_lightspeed_disabled'],
        'aapName': json['aap_name'] == null ? undefined : json['aap_name'],
        'aapNoLog': json['aap_no_log'] == null ? undefined : json['aap_no_log'],
        'aapNs': json['aap_ns'] == null ? undefined : json['aap_ns'],
        'aapRedisMode': json['aap_redis_mode'] == null ? undefined : json['aap_redis_mode'],
        'aapRouteTlsTermination': json['aap_route_tls_termination'] == null ? undefined : json['aap_route_tls_termination'],
    };
}

export function AAPConfigToJSON(json: any): AAPConfig {
    return AAPConfigToJSONTyped(json, false);
}

export function AAPConfigToJSONTyped(value?: AAPConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aapLicenseFile': value['aapLicenseFile'],
        'aap_controller_disabled': value['aapControllerDisabled'],
        'aap_eda_disabled': value['aapEdaDisabled'],
        'aap_hub_disabled': value['aapHubDisabled'],
        'aap_image_pull_policy': value['aapImagePullPolicy'],
        'aap_license_secret': value['aapLicenseSecret'],
        'aap_lightspeed_disabled': value['aapLightspeedDisabled'],
        'aap_name': value['aapName'],
        'aap_no_log': value['aapNoLog'],
        'aap_ns': value['aapNs'],
        'aap_redis_mode': value['aapRedisMode'],
        'aap_route_tls_termination': value['aapRouteTlsTermination'],
    };
}

