/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuthModeOutputBody
 */
export interface AuthModeOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof AuthModeOutputBody
     */
    readonly $schema?: string;
    /**
     * True if authentication is disabled
     * @type {boolean}
     * @memberof AuthModeOutputBody
     */
    noAuth: boolean;
}

/**
 * Check if a given object implements the AuthModeOutputBody interface.
 */
export function instanceOfAuthModeOutputBody(value: object): value is AuthModeOutputBody {
    if (!('noAuth' in value) || value['noAuth'] === undefined) return false;
    return true;
}

export function AuthModeOutputBodyFromJSON(json: any): AuthModeOutputBody {
    return AuthModeOutputBodyFromJSONTyped(json, false);
}

export function AuthModeOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthModeOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'noAuth': json['noAuth'],
    };
}

export function AuthModeOutputBodyToJSON(json: any): AuthModeOutputBody {
    return AuthModeOutputBodyToJSONTyped(json, false);
}

export function AuthModeOutputBodyToJSONTyped(value?: Omit<AuthModeOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'noAuth': value['noAuth'],
    };
}

