/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CertificatesConfig
 */
export interface CertificatesConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CertificatesConfig
     */
    readonly $schema?: string;
    /**
     * PEM-encoded TLS cert for Ironic vmedia HTTPS
     * @type {string}
     * @memberof CertificatesConfig
     */
    ironicHTTPSCertificate?: string;
    /**
     * PEM-encoded private key for Ironic HTTPS cert
     * @type {string}
     * @memberof CertificatesConfig
     */
    ironicHTTPSKey?: string;
    /**
     * PEM-encoded full cert chain for API server
     * @type {string}
     * @memberof CertificatesConfig
     */
    sslAPICertificateFullChain?: string;
    /**
     * PEM-encoded private key for API server cert
     * @type {string}
     * @memberof CertificatesConfig
     */
    sslAPICertificateKey?: string;
    /**
     * PEM-encoded root CA certificate
     * @type {string}
     * @memberof CertificatesConfig
     */
    sslCACertificate?: string;
    /**
     * PEM-encoded full cert chain for ingress wildcard
     * @type {string}
     * @memberof CertificatesConfig
     */
    sslIngressCertificateFullChain?: string;
    /**
     * PEM-encoded private key for ingress cert
     * @type {string}
     * @memberof CertificatesConfig
     */
    sslIngressCertificateKey?: string;
}

/**
 * Check if a given object implements the CertificatesConfig interface.
 */
export function instanceOfCertificatesConfig(value: object): value is CertificatesConfig {
    return true;
}

export function CertificatesConfigFromJSON(json: any): CertificatesConfig {
    return CertificatesConfigFromJSONTyped(json, false);
}

export function CertificatesConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificatesConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'ironicHTTPSCertificate': json['ironicHTTPSCertificate'] == null ? undefined : json['ironicHTTPSCertificate'],
        'ironicHTTPSKey': json['ironicHTTPSKey'] == null ? undefined : json['ironicHTTPSKey'],
        'sslAPICertificateFullChain': json['sslAPICertificateFullChain'] == null ? undefined : json['sslAPICertificateFullChain'],
        'sslAPICertificateKey': json['sslAPICertificateKey'] == null ? undefined : json['sslAPICertificateKey'],
        'sslCACertificate': json['sslCACertificate'] == null ? undefined : json['sslCACertificate'],
        'sslIngressCertificateFullChain': json['sslIngressCertificateFullChain'] == null ? undefined : json['sslIngressCertificateFullChain'],
        'sslIngressCertificateKey': json['sslIngressCertificateKey'] == null ? undefined : json['sslIngressCertificateKey'],
    };
}

export function CertificatesConfigToJSON(json: any): CertificatesConfig {
    return CertificatesConfigToJSONTyped(json, false);
}

export function CertificatesConfigToJSONTyped(value?: Omit<CertificatesConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ironicHTTPSCertificate': value['ironicHTTPSCertificate'],
        'ironicHTTPSKey': value['ironicHTTPSKey'],
        'sslAPICertificateFullChain': value['sslAPICertificateFullChain'],
        'sslAPICertificateKey': value['sslAPICertificateKey'],
        'sslCACertificate': value['sslCACertificate'],
        'sslIngressCertificateFullChain': value['sslIngressCertificateFullChain'],
        'sslIngressCertificateKey': value['sslIngressCertificateKey'],
    };
}

