/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ChangePasswordInputBody
 */
export interface ChangePasswordInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ChangePasswordInputBody
     */
    readonly $schema?: string;
    /**
     * Current password
     * @type {string}
     * @memberof ChangePasswordInputBody
     */
    currentPassword: string;
    /**
     * New password (min 8 characters)
     * @type {string}
     * @memberof ChangePasswordInputBody
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ChangePasswordInputBody interface.
 */
export function instanceOfChangePasswordInputBody(value: object): value is ChangePasswordInputBody {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function ChangePasswordInputBodyFromJSON(json: any): ChangePasswordInputBody {
    return ChangePasswordInputBodyFromJSONTyped(json, false);
}

export function ChangePasswordInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function ChangePasswordInputBodyToJSON(json: any): ChangePasswordInputBody {
    return ChangePasswordInputBodyToJSONTyped(json, false);
}

export function ChangePasswordInputBodyToJSONTyped(value?: Omit<ChangePasswordInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

