/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ChangePasswordOutputBody
 */
export interface ChangePasswordOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ChangePasswordOutputBody
     */
    readonly $schema?: string;
    /**
     * New bearer token (previous tokens are invalidated)
     * @type {string}
     * @memberof ChangePasswordOutputBody
     */
    token: string;
}

/**
 * Check if a given object implements the ChangePasswordOutputBody interface.
 */
export function instanceOfChangePasswordOutputBody(value: object): value is ChangePasswordOutputBody {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ChangePasswordOutputBodyFromJSON(json: any): ChangePasswordOutputBody {
    return ChangePasswordOutputBodyFromJSONTyped(json, false);
}

export function ChangePasswordOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'token': json['token'],
    };
}

export function ChangePasswordOutputBodyToJSON(json: any): ChangePasswordOutputBody {
    return ChangePasswordOutputBodyToJSONTyped(json, false);
}

export function ChangePasswordOutputBodyToJSONTyped(value?: Omit<ChangePasswordOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

