/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HostEntry } from './HostEntry.js';
import {
    HostEntryFromJSON,
    HostEntryFromJSONTyped,
    HostEntryToJSON,
    HostEntryToJSONTyped,
} from './HostEntry.js';

/**
 * 
 * @export
 * @interface CloudInfraConfig
 */
export interface CloudInfraConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CloudInfraConfig
     */
    readonly $schema?: string;
    /**
     * Worker nodes for hardware discovery
     * @type {Array<HostEntry>}
     * @memberof CloudInfraConfig
     */
    discoveryHosts: Array<HostEntry> | null;
}

/**
 * Check if a given object implements the CloudInfraConfig interface.
 */
export function instanceOfCloudInfraConfig(value: object): value is CloudInfraConfig {
    if (!('discoveryHosts' in value) || value['discoveryHosts'] === undefined) return false;
    return true;
}

export function CloudInfraConfigFromJSON(json: any): CloudInfraConfig {
    return CloudInfraConfigFromJSONTyped(json, false);
}

export function CloudInfraConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudInfraConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'discoveryHosts': (json['discovery_hosts'] == null ? null : (json['discovery_hosts'] as Array<any>).map(HostEntryFromJSON)),
    };
}

export function CloudInfraConfigToJSON(json: any): CloudInfraConfig {
    return CloudInfraConfigToJSONTyped(json, false);
}

export function CloudInfraConfigToJSONTyped(value?: Omit<CloudInfraConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'discovery_hosts': (value['discoveryHosts'] == null ? null : (value['discoveryHosts'] as Array<any>).map(HostEntryToJSON)),
    };
}

