/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HostEntry } from './HostEntry.js';
import {
    HostEntryFromJSON,
    HostEntryFromJSONTyped,
    HostEntryToJSON,
    HostEntryToJSONTyped,
} from './HostEntry.js';

/**
 * 
 * @export
 * @interface ClusterConfig
 */
export interface ClusterConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ClusterConfig
     */
    readonly $schema?: string;
    /**
     * Control plane nodes (exactly 3)
     * @type {Array<HostEntry>}
     * @memberof ClusterConfig
     */
    agentHosts: Array<HostEntry> | null;
    /**
     * Virtual IP for Kubernetes API server
     * @type {string}
     * @memberof ClusterConfig
     */
    apiVIP: string;
    /**
     * Base DNS domain for the cluster
     * @type {string}
     * @memberof ClusterConfig
     */
    baseDomain: string;
    /**
     * OpenShift cluster name
     * @type {string}
     * @memberof ClusterConfig
     */
    clusterName: string;
    /**
     * Additional NTP server addresses
     * @type {Array<string>}
     * @memberof ClusterConfig
     */
    defaultNtpServers?: Array<string> | null;
    /**
     * Enable TPM v2 disk encryption
     * @type {boolean}
     * @memberof ClusterConfig
     */
    diskEncryption?: boolean;
    /**
     * Virtual IP for ingress wildcard
     * @type {string}
     * @memberof ClusterConfig
     */
    ingressVIP: string;
    /**
     * Network CIDR for cluster nodes
     * @type {string}
     * @memberof ClusterConfig
     */
    machineNetwork: string;
    /**
     * Maximum pods per node (default: 500)
     * @type {number}
     * @memberof ClusterConfig
     */
    masterMaxPods?: number;
    /**
     * 
     * @type {any}
     * @memberof ClusterConfig
     */
    pullSecret: any | null;
    /**
     * IP of first control-plane node
     * @type {string}
     * @memberof ClusterConfig
     */
    rendezvousIP: string;
    /**
     * Path to SSH public key file
     * @type {string}
     * @memberof ClusterConfig
     */
    sshPubPath: string;
}

/**
 * Check if a given object implements the ClusterConfig interface.
 */
export function instanceOfClusterConfig(value: object): value is ClusterConfig {
    if (!('agentHosts' in value) || value['agentHosts'] === undefined) return false;
    if (!('apiVIP' in value) || value['apiVIP'] === undefined) return false;
    if (!('baseDomain' in value) || value['baseDomain'] === undefined) return false;
    if (!('clusterName' in value) || value['clusterName'] === undefined) return false;
    if (!('ingressVIP' in value) || value['ingressVIP'] === undefined) return false;
    if (!('machineNetwork' in value) || value['machineNetwork'] === undefined) return false;
    if (!('pullSecret' in value) || value['pullSecret'] === undefined) return false;
    if (!('rendezvousIP' in value) || value['rendezvousIP'] === undefined) return false;
    if (!('sshPubPath' in value) || value['sshPubPath'] === undefined) return false;
    return true;
}

export function ClusterConfigFromJSON(json: any): ClusterConfig {
    return ClusterConfigFromJSONTyped(json, false);
}

export function ClusterConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'agentHosts': (json['agent_hosts'] == null ? null : (json['agent_hosts'] as Array<any>).map(HostEntryFromJSON)),
        'apiVIP': json['apiVIP'],
        'baseDomain': json['baseDomain'],
        'clusterName': json['clusterName'],
        'defaultNtpServers': json['defaultNtpServers'] == null ? undefined : json['defaultNtpServers'],
        'diskEncryption': json['diskEncryption'] == null ? undefined : json['diskEncryption'],
        'ingressVIP': json['ingressVIP'],
        'machineNetwork': json['machineNetwork'],
        'masterMaxPods': json['masterMaxPods'] == null ? undefined : json['masterMaxPods'],
        'pullSecret': json['pullSecret'],
        'rendezvousIP': json['rendezvousIP'],
        'sshPubPath': json['sshPubPath'],
    };
}

export function ClusterConfigToJSON(json: any): ClusterConfig {
    return ClusterConfigToJSONTyped(json, false);
}

export function ClusterConfigToJSONTyped(value?: Omit<ClusterConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_hosts': (value['agentHosts'] == null ? null : (value['agentHosts'] as Array<any>).map(HostEntryToJSON)),
        'apiVIP': value['apiVIP'],
        'baseDomain': value['baseDomain'],
        'clusterName': value['clusterName'],
        'defaultNtpServers': value['defaultNtpServers'],
        'diskEncryption': value['diskEncryption'],
        'ingressVIP': value['ingressVIP'],
        'machineNetwork': value['machineNetwork'],
        'masterMaxPods': value['masterMaxPods'],
        'pullSecret': value['pullSecret'],
        'rendezvousIP': value['rendezvousIP'],
        'sshPubPath': value['sshPubPath'],
    };
}

