/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ODFConfig } from './ODFConfig.js';
import {
    ODFConfigFromJSON,
    ODFConfigFromJSONTyped,
    ODFConfigToJSON,
    ODFConfigToJSONTyped,
} from './ODFConfig.js';
import type { LVMSConfig } from './LVMSConfig.js';
import {
    LVMSConfigFromJSON,
    LVMSConfigFromJSONTyped,
    LVMSConfigToJSON,
    LVMSConfigToJSONTyped,
} from './LVMSConfig.js';

/**
 * 
 * @export
 * @interface Defaults
 */
export interface Defaults {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Defaults
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Defaults
     */
    disconnected: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Defaults
     */
    diskEncryption: boolean;
    /**
     * 
     * @type {LVMSConfig}
     * @memberof Defaults
     */
    lvmsDefaults?: LVMSConfig;
    /**
     * 
     * @type {number}
     * @memberof Defaults
     */
    masterMaxPods: number;
    /**
     * 
     * @type {string}
     * @memberof Defaults
     */
    ocMirrorLogLevel: string;
    /**
     * 
     * @type {ODFConfig}
     * @memberof Defaults
     */
    odfDefaults?: ODFConfig;
    /**
     * 
     * @type {string}
     * @memberof Defaults
     */
    storagePlugin: string;
}

/**
 * Check if a given object implements the Defaults interface.
 */
export function instanceOfDefaults(value: object): value is Defaults {
    if (!('disconnected' in value) || value['disconnected'] === undefined) return false;
    if (!('diskEncryption' in value) || value['diskEncryption'] === undefined) return false;
    if (!('masterMaxPods' in value) || value['masterMaxPods'] === undefined) return false;
    if (!('ocMirrorLogLevel' in value) || value['ocMirrorLogLevel'] === undefined) return false;
    if (!('storagePlugin' in value) || value['storagePlugin'] === undefined) return false;
    return true;
}

export function DefaultsFromJSON(json: any): Defaults {
    return DefaultsFromJSONTyped(json, false);
}

export function DefaultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Defaults {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'disconnected': json['disconnected'],
        'diskEncryption': json['diskEncryption'],
        'lvmsDefaults': json['lvmsDefaults'] == null ? undefined : LVMSConfigFromJSON(json['lvmsDefaults']),
        'masterMaxPods': json['masterMaxPods'],
        'ocMirrorLogLevel': json['ocMirrorLogLevel'],
        'odfDefaults': json['odfDefaults'] == null ? undefined : ODFConfigFromJSON(json['odfDefaults']),
        'storagePlugin': json['storagePlugin'],
    };
}

export function DefaultsToJSON(json: any): Defaults {
    return DefaultsToJSONTyped(json, false);
}

export function DefaultsToJSONTyped(value?: Omit<Defaults, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disconnected': value['disconnected'],
        'diskEncryption': value['diskEncryption'],
        'lvmsDefaults': LVMSConfigToJSON(value['lvmsDefaults']),
        'masterMaxPods': value['masterMaxPods'],
        'ocMirrorLogLevel': value['ocMirrorLogLevel'],
        'odfDefaults': ODFConfigToJSON(value['odfDefaults']),
        'storagePlugin': value['storagePlugin'],
    };
}

