/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DeploymentPhase } from './DeploymentPhase.js';
import {
    DeploymentPhaseFromJSON,
    DeploymentPhaseFromJSONTyped,
    DeploymentPhaseToJSON,
    DeploymentPhaseToJSONTyped,
} from './DeploymentPhase.js';

/**
 * 
 * @export
 * @interface Deployment
 */
export interface Deployment {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Deployment
     */
    readonly $schema?: string;
    /**
     * Deployment identifier
     * @type {string}
     * @memberof Deployment
     */
    id: string;
    /**
     * Ordered list of deployment phases
     * @type {Array<DeploymentPhase>}
     * @memberof Deployment
     */
    phases: Array<DeploymentPhase> | null;
    /**
     * When the deployment was started
     * @type {Date}
     * @memberof Deployment
     */
    startedAt: Date;
    /**
     * Overall deployment status
     * @type {string}
     * @memberof Deployment
     */
    status: string;
    /**
     * Estimated total ansible tasks across all phases
     * @type {number}
     * @memberof Deployment
     */
    totalTasks: number;
}

/**
 * Check if a given object implements the Deployment interface.
 */
export function instanceOfDeployment(value: object): value is Deployment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('phases' in value) || value['phases'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalTasks' in value) || value['totalTasks'] === undefined) return false;
    return true;
}

export function DeploymentFromJSON(json: any): Deployment {
    return DeploymentFromJSONTyped(json, false);
}

export function DeploymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Deployment {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'id': json['id'],
        'phases': (json['phases'] == null ? null : (json['phases'] as Array<any>).map(DeploymentPhaseFromJSON)),
        'startedAt': (new Date(json['startedAt'])),
        'status': json['status'],
        'totalTasks': json['totalTasks'],
    };
}

export function DeploymentToJSON(json: any): Deployment {
    return DeploymentToJSONTyped(json, false);
}

export function DeploymentToJSONTyped(value?: Omit<Deployment, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'phases': (value['phases'] == null ? null : (value['phases'] as Array<any>).map(DeploymentPhaseToJSON)),
        'startedAt': value['startedAt'].toISOString(),
        'status': value['status'],
        'totalTasks': value['totalTasks'],
    };
}

