/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DeploymentProgress
 */
export interface DeploymentProgress {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DeploymentProgress
     */
    readonly $schema?: string;
    /**
     * Number of completed ansible tasks
     * @type {number}
     * @memberof DeploymentProgress
     */
    completed: number;
    /**
     * Name of the currently running phase
     * @type {string}
     * @memberof DeploymentProgress
     */
    currentPhase: string;
    /**
     * Name of the currently running ansible task
     * @type {string}
     * @memberof DeploymentProgress
     */
    currentTask: string;
    /**
     * Completion percentage (0-100)
     * @type {number}
     * @memberof DeploymentProgress
     */
    percentage: number;
    /**
     * Estimated total tasks
     * @type {number}
     * @memberof DeploymentProgress
     */
    total: number;
}

/**
 * Check if a given object implements the DeploymentProgress interface.
 */
export function instanceOfDeploymentProgress(value: object): value is DeploymentProgress {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('currentPhase' in value) || value['currentPhase'] === undefined) return false;
    if (!('currentTask' in value) || value['currentTask'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function DeploymentProgressFromJSON(json: any): DeploymentProgress {
    return DeploymentProgressFromJSONTyped(json, false);
}

export function DeploymentProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentProgress {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'completed': json['completed'],
        'currentPhase': json['currentPhase'],
        'currentTask': json['currentTask'],
        'percentage': json['percentage'],
        'total': json['total'],
    };
}

export function DeploymentProgressToJSON(json: any): DeploymentProgress {
    return DeploymentProgressToJSONTyped(json, false);
}

export function DeploymentProgressToJSONTyped(value?: Omit<DeploymentProgress, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'currentPhase': value['currentPhase'],
        'currentTask': value['currentTask'],
        'percentage': value['percentage'],
        'total': value['total'],
    };
}

