/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DeploymentPhase
 */
export interface DeploymentPhase {
    /**
     * Phase name (main, trust-manager, osac, etc.)
     * @type {string}
     * @memberof DeploymentPhase
     */
    name: string;
    /**
     * Phase status
     * @type {string}
     * @memberof DeploymentPhase
     */
    status: DeploymentPhaseStatusEnum;
    /**
     * Task run ID for this phase
     * @type {string}
     * @memberof DeploymentPhase
     */
    taskId?: string;
}


/**
 * @export
 */
export const DeploymentPhaseStatusEnum = {
    Pending: 'pending',
    Running: 'running',
    Successful: 'successful',
    Failed: 'failed'
} as const;
export type DeploymentPhaseStatusEnum = typeof DeploymentPhaseStatusEnum[keyof typeof DeploymentPhaseStatusEnum];


/**
 * Check if a given object implements the DeploymentPhase interface.
 */
export function instanceOfDeploymentPhase(value: object): value is DeploymentPhase {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DeploymentPhaseFromJSON(json: any): DeploymentPhase {
    return DeploymentPhaseFromJSONTyped(json, false);
}

export function DeploymentPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentPhase {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': json['status'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function DeploymentPhaseToJSON(json: any): DeploymentPhase {
    return DeploymentPhaseToJSONTyped(json, false);
}

export function DeploymentPhaseToJSONTyped(value?: DeploymentPhase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': value['status'],
        'taskId': value['taskId'],
    };
}

