/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CloudInfraConfig } from './CloudInfraConfig.js';
import {
    CloudInfraConfigFromJSON,
    CloudInfraConfigFromJSONTyped,
    CloudInfraConfigToJSON,
    CloudInfraConfigToJSONTyped,
} from './CloudInfraConfig.js';
import type { CertificatesConfig } from './CertificatesConfig.js';
import {
    CertificatesConfigFromJSON,
    CertificatesConfigFromJSONTyped,
    CertificatesConfigToJSON,
    CertificatesConfigToJSONTyped,
} from './CertificatesConfig.js';
import type { GlobalConfig } from './GlobalConfig.js';
import {
    GlobalConfigFromJSON,
    GlobalConfigFromJSONTyped,
    GlobalConfigToJSON,
    GlobalConfigToJSONTyped,
} from './GlobalConfig.js';

/**
 * 
 * @export
 * @interface EnclaveConfig
 */
export interface EnclaveConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof EnclaveConfig
     */
    readonly $schema?: string;
    /**
     * TLS certificates (certificates.yaml)
     * @type {CertificatesConfig}
     * @memberof EnclaveConfig
     */
    certificates: CertificatesConfig;
    /**
     * Cloud infrastructure / discovery hosts (cloud_infra.yaml)
     * @type {CloudInfraConfig}
     * @memberof EnclaveConfig
     */
    cloudInfra: CloudInfraConfig;
    /**
     * Primary cluster configuration (global.yaml)
     * @type {GlobalConfig}
     * @memberof EnclaveConfig
     */
    global: GlobalConfig;
}

/**
 * Check if a given object implements the EnclaveConfig interface.
 */
export function instanceOfEnclaveConfig(value: object): value is EnclaveConfig {
    if (!('certificates' in value) || value['certificates'] === undefined) return false;
    if (!('cloudInfra' in value) || value['cloudInfra'] === undefined) return false;
    if (!('global' in value) || value['global'] === undefined) return false;
    return true;
}

export function EnclaveConfigFromJSON(json: any): EnclaveConfig {
    return EnclaveConfigFromJSONTyped(json, false);
}

export function EnclaveConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnclaveConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'certificates': CertificatesConfigFromJSON(json['certificates']),
        'cloudInfra': CloudInfraConfigFromJSON(json['cloudInfra']),
        'global': GlobalConfigFromJSON(json['global']),
    };
}

export function EnclaveConfigToJSON(json: any): EnclaveConfig {
    return EnclaveConfigToJSONTyped(json, false);
}

export function EnclaveConfigToJSONTyped(value?: Omit<EnclaveConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certificates': CertificatesConfigToJSON(value['certificates']),
        'cloudInfra': CloudInfraConfigToJSON(value['cloudInfra']),
        'global': GlobalConfigToJSON(value['global']),
    };
}

