/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Experience } from './Experience.js';
import {
    ExperienceFromJSON,
    ExperienceFromJSONTyped,
    ExperienceToJSON,
    ExperienceToJSONTyped,
} from './Experience.js';

/**
 * 
 * @export
 * @interface ExperiencesOutputBody
 */
export interface ExperiencesOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ExperiencesOutputBody
     */
    readonly $schema?: string;
    /**
     * Available experience definitions
     * @type {Array<Experience>}
     * @memberof ExperiencesOutputBody
     */
    experiences: Array<Experience> | null;
}

/**
 * Check if a given object implements the ExperiencesOutputBody interface.
 */
export function instanceOfExperiencesOutputBody(value: object): value is ExperiencesOutputBody {
    if (!('experiences' in value) || value['experiences'] === undefined) return false;
    return true;
}

export function ExperiencesOutputBodyFromJSON(json: any): ExperiencesOutputBody {
    return ExperiencesOutputBodyFromJSONTyped(json, false);
}

export function ExperiencesOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperiencesOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'experiences': (json['experiences'] == null ? null : (json['experiences'] as Array<any>).map(ExperienceFromJSON)),
    };
}

export function ExperiencesOutputBodyToJSON(json: any): ExperiencesOutputBody {
    return ExperiencesOutputBodyToJSONTyped(json, false);
}

export function ExperiencesOutputBodyToJSONTyped(value?: Omit<ExperiencesOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiences': (value['experiences'] == null ? null : (value['experiences'] as Array<any>).map(ExperienceToJSON)),
    };
}

