/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExperiencePlugin } from './ExperiencePlugin.js';
import {
    ExperiencePluginFromJSON,
    ExperiencePluginFromJSONTyped,
    ExperiencePluginToJSON,
    ExperiencePluginToJSONTyped,
} from './ExperiencePlugin.js';

/**
 * 
 * @export
 * @interface Experience
 */
export interface Experience {
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    name: string;
    /**
     * 
     * @type {Array<ExperiencePlugin>}
     * @memberof Experience
     */
    plugins: Array<ExperiencePlugin> | null;
}

/**
 * Check if a given object implements the Experience interface.
 */
export function instanceOfExperience(value: object): value is Experience {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('plugins' in value) || value['plugins'] === undefined) return false;
    return true;
}

export function ExperienceFromJSON(json: any): Experience {
    return ExperienceFromJSONTyped(json, false);
}

export function ExperienceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Experience {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'id': json['id'],
        'name': json['name'],
        'plugins': (json['plugins'] == null ? null : (json['plugins'] as Array<any>).map(ExperiencePluginFromJSON)),
    };
}

export function ExperienceToJSON(json: any): Experience {
    return ExperienceToJSONTyped(json, false);
}

export function ExperienceToJSONTyped(value?: Experience | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'plugins': (value['plugins'] == null ? null : (value['plugins'] as Array<any>).map(ExperiencePluginToJSON)),
    };
}

