/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExperiencePlugin
 */
export interface ExperiencePlugin {
    /**
     * 
     * @type {string}
     * @memberof ExperiencePlugin
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ExperiencePlugin
     */
    order?: number;
}

/**
 * Check if a given object implements the ExperiencePlugin interface.
 */
export function instanceOfExperiencePlugin(value: object): value is ExperiencePlugin {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExperiencePluginFromJSON(json: any): ExperiencePlugin {
    return ExperiencePluginFromJSONTyped(json, false);
}

export function ExperiencePluginFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperiencePlugin {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function ExperiencePluginToJSON(json: any): ExperiencePlugin {
    return ExperiencePluginToJSONTyped(json, false);
}

export function ExperiencePluginToJSONTyped(value?: ExperiencePlugin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'order': value['order'],
    };
}

