/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface FileUploadOutputBody
 */
export interface FileUploadOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof FileUploadOutputBody
     */
    readonly $schema?: string;
    /**
     * Absolute path where the file was written
     * @type {string}
     * @memberof FileUploadOutputBody
     */
    path: string;
}

/**
 * Check if a given object implements the FileUploadOutputBody interface.
 */
export function instanceOfFileUploadOutputBody(value: object): value is FileUploadOutputBody {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function FileUploadOutputBodyFromJSON(json: any): FileUploadOutputBody {
    return FileUploadOutputBodyFromJSONTyped(json, false);
}

export function FileUploadOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileUploadOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'path': json['path'],
    };
}

export function FileUploadOutputBodyToJSON(json: any): FileUploadOutputBody {
    return FileUploadOutputBodyToJSONTyped(json, false);
}

export function FileUploadOutputBodyToJSONTyped(value?: Omit<FileUploadOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
    };
}

