/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetTaskEventsOutputBody
 */
export interface GetTaskEventsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetTaskEventsOutputBody
     */
    readonly $schema?: string;
    /**
     * Ansible Runner job events
     * @type {Array<any>}
     * @memberof GetTaskEventsOutputBody
     */
    events: Array<any> | null;
}

/**
 * Check if a given object implements the GetTaskEventsOutputBody interface.
 */
export function instanceOfGetTaskEventsOutputBody(value: object): value is GetTaskEventsOutputBody {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function GetTaskEventsOutputBodyFromJSON(json: any): GetTaskEventsOutputBody {
    return GetTaskEventsOutputBodyFromJSONTyped(json, false);
}

export function GetTaskEventsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTaskEventsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'events': json['events'] == null ? null : json['events'],
    };
}

export function GetTaskEventsOutputBodyToJSON(json: any): GetTaskEventsOutputBody {
    return GetTaskEventsOutputBodyToJSONTyped(json, false);
}

export function GetTaskEventsOutputBodyToJSONTyped(value?: Omit<GetTaskEventsOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
    };
}

