/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HostEntry
 */
export interface HostEntry {
    /**
     * Redfish system ID path component (default: 1)
     * @type {string}
     * @memberof HostEntry
     */
    bmcSystemId?: string;
    /**
     * Node IPv4 address within machineNetwork
     * @type {string}
     * @memberof HostEntry
     */
    ipAddress: string;
    /**
     * MAC address (xx:xx:xx:xx:xx:xx)
     * @type {string}
     * @memberof HostEntry
     */
    macAddress: string;
    /**
     * 
     * @type {any}
     * @memberof HostEntry
     */
    mapInterfaces?: any | null;
    /**
     * Node name label
     * @type {string}
     * @memberof HostEntry
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof HostEntry
     */
    networkConfig?: any | null;
    /**
     * Redfish/IPMI management IP
     * @type {string}
     * @memberof HostEntry
     */
    redfish: string;
    /**
     * Redfish password
     * @type {string}
     * @memberof HostEntry
     */
    redfishPassword: string;
    /**
     * Redfish username
     * @type {string}
     * @memberof HostEntry
     */
    redfishUser: string;
    /**
     * Root disk path for OS installation
     * @type {string}
     * @memberof HostEntry
     */
    rootDisk: string;
}

/**
 * Check if a given object implements the HostEntry interface.
 */
export function instanceOfHostEntry(value: object): value is HostEntry {
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('macAddress' in value) || value['macAddress'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('redfish' in value) || value['redfish'] === undefined) return false;
    if (!('redfishPassword' in value) || value['redfishPassword'] === undefined) return false;
    if (!('redfishUser' in value) || value['redfishUser'] === undefined) return false;
    if (!('rootDisk' in value) || value['rootDisk'] === undefined) return false;
    return true;
}

export function HostEntryFromJSON(json: any): HostEntry {
    return HostEntryFromJSONTyped(json, false);
}

export function HostEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'bmcSystemId': json['bmcSystemId'] == null ? undefined : json['bmcSystemId'],
        'ipAddress': json['ipAddress'],
        'macAddress': json['macAddress'],
        'mapInterfaces': json['mapInterfaces'] == null ? undefined : json['mapInterfaces'],
        'name': json['name'],
        'networkConfig': json['networkConfig'] == null ? undefined : json['networkConfig'],
        'redfish': json['redfish'],
        'redfishPassword': json['redfishPassword'],
        'redfishUser': json['redfishUser'],
        'rootDisk': json['rootDisk'],
    };
}

export function HostEntryToJSON(json: any): HostEntry {
    return HostEntryToJSONTyped(json, false);
}

export function HostEntryToJSONTyped(value?: HostEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bmcSystemId': value['bmcSystemId'],
        'ipAddress': value['ipAddress'],
        'macAddress': value['macAddress'],
        'mapInterfaces': value['mapInterfaces'],
        'name': value['name'],
        'networkConfig': value['networkConfig'],
        'redfish': value['redfish'],
        'redfishPassword': value['redfishPassword'],
        'redfishUser': value['redfishUser'],
        'rootDisk': value['rootDisk'],
    };
}

