/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LandingZoneConfig
 */
export interface LandingZoneConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LandingZoneConfig
     */
    readonly $schema?: string;
    /**
     * Air-gapped deployment mode (default: true)
     * @type {boolean}
     * @memberof LandingZoneConfig
     */
    disconnected?: boolean;
    /**
     * DNS hostname for landing zone BMC interface
     * @type {string}
     * @memberof LandingZoneConfig
     */
    lzBmcHostname?: string;
    /**
     * Landing zone BMC IP for boot ISO serving
     * @type {string}
     * @memberof LandingZoneConfig
     */
    lzBmcIP: string;
    /**
     * Absolute path to root working directory
     * @type {string}
     * @memberof LandingZoneConfig
     */
    workingDir: string;
}

/**
 * Check if a given object implements the LandingZoneConfig interface.
 */
export function instanceOfLandingZoneConfig(value: object): value is LandingZoneConfig {
    if (!('lzBmcIP' in value) || value['lzBmcIP'] === undefined) return false;
    if (!('workingDir' in value) || value['workingDir'] === undefined) return false;
    return true;
}

export function LandingZoneConfigFromJSON(json: any): LandingZoneConfig {
    return LandingZoneConfigFromJSONTyped(json, false);
}

export function LandingZoneConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LandingZoneConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'disconnected': json['disconnected'] == null ? undefined : json['disconnected'],
        'lzBmcHostname': json['lzBmcHostname'] == null ? undefined : json['lzBmcHostname'],
        'lzBmcIP': json['lzBmcIP'],
        'workingDir': json['workingDir'],
    };
}

export function LandingZoneConfigToJSON(json: any): LandingZoneConfig {
    return LandingZoneConfigToJSONTyped(json, false);
}

export function LandingZoneConfigToJSONTyped(value?: Omit<LandingZoneConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disconnected': value['disconnected'],
        'lzBmcHostname': value['lzBmcHostname'],
        'lzBmcIP': value['lzBmcIP'],
        'workingDir': value['workingDir'],
    };
}

