/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TaskRun } from './TaskRun.js';
import {
    TaskRunFromJSON,
    TaskRunFromJSONTyped,
    TaskRunToJSON,
    TaskRunToJSONTyped,
} from './TaskRun.js';

/**
 * 
 * @export
 * @interface ListTasksOutputBody
 */
export interface ListTasksOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ListTasksOutputBody
     */
    readonly $schema?: string;
    /**
     * All known task runs
     * @type {Array<TaskRun>}
     * @memberof ListTasksOutputBody
     */
    runs: Array<TaskRun> | null;
}

/**
 * Check if a given object implements the ListTasksOutputBody interface.
 */
export function instanceOfListTasksOutputBody(value: object): value is ListTasksOutputBody {
    if (!('runs' in value) || value['runs'] === undefined) return false;
    return true;
}

export function ListTasksOutputBodyFromJSON(json: any): ListTasksOutputBody {
    return ListTasksOutputBodyFromJSONTyped(json, false);
}

export function ListTasksOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTasksOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'runs': (json['runs'] == null ? null : (json['runs'] as Array<any>).map(TaskRunFromJSON)),
    };
}

export function ListTasksOutputBodyToJSON(json: any): ListTasksOutputBody {
    return ListTasksOutputBodyToJSONTyped(json, false);
}

export function ListTasksOutputBodyToJSONTyped(value?: Omit<ListTasksOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runs': (value['runs'] == null ? null : (value['runs'] as Array<any>).map(TaskRunToJSON)),
    };
}

