/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LoginInputBody
 */
export interface LoginInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LoginInputBody
     */
    readonly $schema?: string;
    /**
     * Password
     * @type {string}
     * @memberof LoginInputBody
     */
    password: string;
    /**
     * Username (always 'admin')
     * @type {string}
     * @memberof LoginInputBody
     */
    username: string;
}

/**
 * Check if a given object implements the LoginInputBody interface.
 */
export function instanceOfLoginInputBody(value: object): value is LoginInputBody {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function LoginInputBodyFromJSON(json: any): LoginInputBody {
    return LoginInputBodyFromJSONTyped(json, false);
}

export function LoginInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'password': json['password'],
        'username': json['username'],
    };
}

export function LoginInputBodyToJSON(json: any): LoginInputBody {
    return LoginInputBodyToJSONTyped(json, false);
}

export function LoginInputBodyToJSONTyped(value?: Omit<LoginInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

