/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LoginOutputBody
 */
export interface LoginOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LoginOutputBody
     */
    readonly $schema?: string;
    /**
     * True if the initial password has not been changed yet
     * @type {boolean}
     * @memberof LoginOutputBody
     */
    mustChangePassword: boolean;
    /**
     * Bearer token for API access
     * @type {string}
     * @memberof LoginOutputBody
     */
    token: string;
}

/**
 * Check if a given object implements the LoginOutputBody interface.
 */
export function instanceOfLoginOutputBody(value: object): value is LoginOutputBody {
    if (!('mustChangePassword' in value) || value['mustChangePassword'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginOutputBodyFromJSON(json: any): LoginOutputBody {
    return LoginOutputBodyFromJSONTyped(json, false);
}

export function LoginOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'mustChangePassword': json['mustChangePassword'],
        'token': json['token'],
    };
}

export function LoginOutputBodyToJSON(json: any): LoginOutputBody {
    return LoginOutputBodyToJSONTyped(json, false);
}

export function LoginOutputBodyToJSONTyped(value?: Omit<LoginOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mustChangePassword': value['mustChangePassword'],
        'token': value['token'],
    };
}

