/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LVMSThinPoolConfig } from './LVMSThinPoolConfig.js';
import {
    LVMSThinPoolConfigFromJSON,
    LVMSThinPoolConfigFromJSONTyped,
    LVMSThinPoolConfigToJSON,
    LVMSThinPoolConfigToJSONTyped,
} from './LVMSThinPoolConfig.js';

/**
 * 
 * @export
 * @interface LVMSConfig
 */
export interface LVMSConfig {
    /**
     * Set as default StorageClass
     * @type {boolean}
     * @memberof LVMSConfig
     */
    defaultStorageClass: boolean;
    /**
     * LVM volume group device class name
     * @type {string}
     * @memberof LVMSConfig
     */
    deviceClassName: string;
    /**
     * Thin pool settings
     * @type {LVMSThinPoolConfig}
     * @memberof LVMSConfig
     */
    thinPoolConfig: LVMSThinPoolConfig;
}

/**
 * Check if a given object implements the LVMSConfig interface.
 */
export function instanceOfLVMSConfig(value: object): value is LVMSConfig {
    if (!('defaultStorageClass' in value) || value['defaultStorageClass'] === undefined) return false;
    if (!('deviceClassName' in value) || value['deviceClassName'] === undefined) return false;
    if (!('thinPoolConfig' in value) || value['thinPoolConfig'] === undefined) return false;
    return true;
}

export function LVMSConfigFromJSON(json: any): LVMSConfig {
    return LVMSConfigFromJSONTyped(json, false);
}

export function LVMSConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LVMSConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultStorageClass': json['defaultStorageClass'],
        'deviceClassName': json['deviceClassName'],
        'thinPoolConfig': LVMSThinPoolConfigFromJSON(json['thinPoolConfig']),
    };
}

export function LVMSConfigToJSON(json: any): LVMSConfig {
    return LVMSConfigToJSONTyped(json, false);
}

export function LVMSConfigToJSONTyped(value?: LVMSConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaultStorageClass': value['defaultStorageClass'],
        'deviceClassName': value['deviceClassName'],
        'thinPoolConfig': LVMSThinPoolConfigToJSON(value['thinPoolConfig']),
    };
}

