/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LVMSThinPoolConfig
 */
export interface LVMSThinPoolConfig {
    /**
     * Thin pool name
     * @type {string}
     * @memberof LVMSThinPoolConfig
     */
    name: string;
    /**
     * Thin pool overprovisioning ratio
     * @type {number}
     * @memberof LVMSThinPoolConfig
     */
    overprovisionRatio: number;
    /**
     * Pool size as percentage of volume group
     * @type {number}
     * @memberof LVMSThinPoolConfig
     */
    sizePercent: number;
}

/**
 * Check if a given object implements the LVMSThinPoolConfig interface.
 */
export function instanceOfLVMSThinPoolConfig(value: object): value is LVMSThinPoolConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('overprovisionRatio' in value) || value['overprovisionRatio'] === undefined) return false;
    if (!('sizePercent' in value) || value['sizePercent'] === undefined) return false;
    return true;
}

export function LVMSThinPoolConfigFromJSON(json: any): LVMSThinPoolConfig {
    return LVMSThinPoolConfigFromJSONTyped(json, false);
}

export function LVMSThinPoolConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LVMSThinPoolConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'overprovisionRatio': json['overprovisionRatio'],
        'sizePercent': json['sizePercent'],
    };
}

export function LVMSThinPoolConfigToJSON(json: any): LVMSThinPoolConfig {
    return LVMSThinPoolConfigToJSONTyped(json, false);
}

export function LVMSThinPoolConfigToJSONTyped(value?: LVMSThinPoolConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'overprovisionRatio': value['overprovisionRatio'],
        'sizePercent': value['sizePercent'],
    };
}

