/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LVMSDeviceSelector
 */
export interface LVMSDeviceSelector {
    /**
     * Disk device paths for LVM volume group
     * @type {Array<string>}
     * @memberof LVMSDeviceSelector
     */
    optionalPaths?: Array<string> | null;
}

/**
 * Check if a given object implements the LVMSDeviceSelector interface.
 */
export function instanceOfLVMSDeviceSelector(value: object): value is LVMSDeviceSelector {
    return true;
}

export function LVMSDeviceSelectorFromJSON(json: any): LVMSDeviceSelector {
    return LVMSDeviceSelectorFromJSONTyped(json, false);
}

export function LVMSDeviceSelectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LVMSDeviceSelector {
    if (json == null) {
        return json;
    }
    return {
        
        'optionalPaths': json['optionalPaths'] == null ? undefined : json['optionalPaths'],
    };
}

export function LVMSDeviceSelectorToJSON(json: any): LVMSDeviceSelector {
    return LVMSDeviceSelectorToJSONTyped(json, false);
}

export function LVMSDeviceSelectorToJSONTyped(value?: LVMSDeviceSelector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'optionalPaths': value['optionalPaths'],
    };
}

