/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LVMSDeviceSelector } from './LVMSDeviceSelector.js';
import {
    LVMSDeviceSelectorFromJSON,
    LVMSDeviceSelectorFromJSONTyped,
    LVMSDeviceSelectorToJSON,
    LVMSDeviceSelectorToJSONTyped,
} from './LVMSDeviceSelector.js';

/**
 * 
 * @export
 * @interface LVMSStorageConfig
 */
export interface LVMSStorageConfig {
    /**
     * LVMS device selector
     * @type {LVMSDeviceSelector}
     * @memberof LVMSStorageConfig
     */
    deviceSelector: LVMSDeviceSelector;
}

/**
 * Check if a given object implements the LVMSStorageConfig interface.
 */
export function instanceOfLVMSStorageConfig(value: object): value is LVMSStorageConfig {
    if (!('deviceSelector' in value) || value['deviceSelector'] === undefined) return false;
    return true;
}

export function LVMSStorageConfigFromJSON(json: any): LVMSStorageConfig {
    return LVMSStorageConfigFromJSONTyped(json, false);
}

export function LVMSStorageConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LVMSStorageConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceSelector': LVMSDeviceSelectorFromJSON(json['deviceSelector']),
    };
}

export function LVMSStorageConfigToJSON(json: any): LVMSStorageConfig {
    return LVMSStorageConfigToJSONTyped(json, false);
}

export function LVMSStorageConfigToJSONTyped(value?: LVMSStorageConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceSelector': LVMSDeviceSelectorToJSON(value['deviceSelector']),
    };
}

