/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface NetworkConfig
 */
export interface NetworkConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof NetworkConfig
     */
    readonly $schema?: string;
    /**
     * DNS server IP for cluster nodes
     * @type {string}
     * @memberof NetworkConfig
     */
    defaultDNS: string;
    /**
     * Default gateway IP for cluster nodes
     * @type {string}
     * @memberof NetworkConfig
     */
    defaultGateway: string;
    /**
     * Subnet prefix length
     * @type {number}
     * @memberof NetworkConfig
     */
    defaultPrefix: number;
}

/**
 * Check if a given object implements the NetworkConfig interface.
 */
export function instanceOfNetworkConfig(value: object): value is NetworkConfig {
    if (!('defaultDNS' in value) || value['defaultDNS'] === undefined) return false;
    if (!('defaultGateway' in value) || value['defaultGateway'] === undefined) return false;
    if (!('defaultPrefix' in value) || value['defaultPrefix'] === undefined) return false;
    return true;
}

export function NetworkConfigFromJSON(json: any): NetworkConfig {
    return NetworkConfigFromJSONTyped(json, false);
}

export function NetworkConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'defaultDNS': json['defaultDNS'],
        'defaultGateway': json['defaultGateway'],
        'defaultPrefix': json['defaultPrefix'],
    };
}

export function NetworkConfigToJSON(json: any): NetworkConfig {
    return NetworkConfigToJSONTyped(json, false);
}

export function NetworkConfigToJSONTyped(value?: Omit<NetworkConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaultDNS': value['defaultDNS'],
        'defaultGateway': value['defaultGateway'],
        'defaultPrefix': value['defaultPrefix'],
    };
}

