/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ODFConfig
 */
export interface ODFConfig {
    /**
     * Set as default StorageClass
     * @type {boolean}
     * @memberof ODFConfig
     */
    defaultStorageClass: boolean;
}

/**
 * Check if a given object implements the ODFConfig interface.
 */
export function instanceOfODFConfig(value: object): value is ODFConfig {
    if (!('defaultStorageClass' in value) || value['defaultStorageClass'] === undefined) return false;
    return true;
}

export function ODFConfigFromJSON(json: any): ODFConfig {
    return ODFConfigFromJSONTyped(json, false);
}

export function ODFConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ODFConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultStorageClass': json['defaultStorageClass'],
    };
}

export function ODFConfigToJSON(json: any): ODFConfig {
    return ODFConfigToJSONTyped(json, false);
}

export function ODFConfigToJSONTyped(value?: ODFConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaultStorageClass': value['defaultStorageClass'],
    };
}

