/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Plugin
 */
export interface Plugin {
    /**
     * Plugin default configuration values
     * @type {{ [key: string]: any; }}
     * @memberof Plugin
     */
    defaults?: { [key: string]: any; };
    /**
     * Plugin identifier
     * @type {string}
     * @memberof Plugin
     */
    name: string;
    /**
     * Deployment order within type
     * @type {number}
     * @memberof Plugin
     */
    order?: number;
    /**
     * Plugin type
     * @type {string}
     * @memberof Plugin
     */
    type: PluginTypeEnum;
}


/**
 * @export
 */
export const PluginTypeEnum = {
    Foundation: 'foundation',
    Addon: 'addon'
} as const;
export type PluginTypeEnum = typeof PluginTypeEnum[keyof typeof PluginTypeEnum];


/**
 * Check if a given object implements the Plugin interface.
 */
export function instanceOfPlugin(value: object): value is Plugin {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PluginFromJSON(json: any): Plugin {
    return PluginFromJSONTyped(json, false);
}

export function PluginFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plugin {
    if (json == null) {
        return json;
    }
    return {
        
        'defaults': json['defaults'] == null ? undefined : json['defaults'],
        'name': json['name'],
        'order': json['order'] == null ? undefined : json['order'],
        'type': json['type'],
    };
}

export function PluginToJSON(json: any): Plugin {
    return PluginToJSONTyped(json, false);
}

export function PluginToJSONTyped(value?: Plugin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaults': value['defaults'],
        'name': value['name'],
        'order': value['order'],
        'type': value['type'],
    };
}

