/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Plugin } from './Plugin.js';
import {
    PluginFromJSON,
    PluginFromJSONTyped,
    PluginToJSON,
    PluginToJSONTyped,
} from './Plugin.js';

/**
 * 
 * @export
 * @interface PluginsOutputBody
 */
export interface PluginsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PluginsOutputBody
     */
    readonly $schema?: string;
    /**
     * Available plugins
     * @type {Array<Plugin>}
     * @memberof PluginsOutputBody
     */
    plugins: Array<Plugin> | null;
}

/**
 * Check if a given object implements the PluginsOutputBody interface.
 */
export function instanceOfPluginsOutputBody(value: object): value is PluginsOutputBody {
    if (!('plugins' in value) || value['plugins'] === undefined) return false;
    return true;
}

export function PluginsOutputBodyFromJSON(json: any): PluginsOutputBody {
    return PluginsOutputBodyFromJSONTyped(json, false);
}

export function PluginsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'plugins': (json['plugins'] == null ? null : (json['plugins'] as Array<any>).map(PluginFromJSON)),
    };
}

export function PluginsOutputBodyToJSON(json: any): PluginsOutputBody {
    return PluginsOutputBodyToJSONTyped(json, false);
}

export function PluginsOutputBodyToJSONTyped(value?: Omit<PluginsOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plugins': (value['plugins'] == null ? null : (value['plugins'] as Array<any>).map(PluginToJSON)),
    };
}

