/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ValidationError } from './ValidationError.js';
import {
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
    ValidationErrorToJSONTyped,
} from './ValidationError.js';

/**
 * 
 * @export
 * @interface PluginValidateOutputBody
 */
export interface PluginValidateOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PluginValidateOutputBody
     */
    readonly $schema?: string;
    /**
     * Validation errors, if any
     * @type {Array<ValidationError>}
     * @memberof PluginValidateOutputBody
     */
    errors?: Array<ValidationError> | null;
    /**
     * Whether the combination is valid
     * @type {boolean}
     * @memberof PluginValidateOutputBody
     */
    valid: boolean;
}

/**
 * Check if a given object implements the PluginValidateOutputBody interface.
 */
export function instanceOfPluginValidateOutputBody(value: object): value is PluginValidateOutputBody {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function PluginValidateOutputBodyFromJSON(json: any): PluginValidateOutputBody {
    return PluginValidateOutputBodyFromJSONTyped(json, false);
}

export function PluginValidateOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginValidateOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ValidationErrorFromJSON)),
        'valid': json['valid'],
    };
}

export function PluginValidateOutputBodyToJSON(json: any): PluginValidateOutputBody {
    return PluginValidateOutputBodyToJSONTyped(json, false);
}

export function PluginValidateOutputBodyToJSONTyped(value?: Omit<PluginValidateOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ValidationErrorToJSON)),
        'valid': value['valid'],
    };
}

