/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PluginValidateInputBody
 */
export interface PluginValidateInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PluginValidateInputBody
     */
    readonly $schema?: string;
    /**
     * Plugin names to validate as a combination
     * @type {Array<string>}
     * @memberof PluginValidateInputBody
     */
    plugins: Array<string> | null;
}

/**
 * Check if a given object implements the PluginValidateInputBody interface.
 */
export function instanceOfPluginValidateInputBody(value: object): value is PluginValidateInputBody {
    if (!('plugins' in value) || value['plugins'] === undefined) return false;
    return true;
}

export function PluginValidateInputBodyFromJSON(json: any): PluginValidateInputBody {
    return PluginValidateInputBodyFromJSONTyped(json, false);
}

export function PluginValidateInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginValidateInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'plugins': json['plugins'] == null ? null : json['plugins'],
    };
}

export function PluginValidateInputBodyToJSON(json: any): PluginValidateInputBody {
    return PluginValidateInputBodyToJSONTyped(json, false);
}

export function PluginValidateInputBodyToJSONTyped(value?: Omit<PluginValidateInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plugins': value['plugins'],
    };
}

