/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ODFConfig } from './ODFConfig.js';
import {
    ODFConfigFromJSON,
    ODFConfigFromJSONTyped,
    ODFConfigToJSON,
    ODFConfigToJSONTyped,
} from './ODFConfig.js';
import type { LVMSConfig } from './LVMSConfig.js';
import {
    LVMSConfigFromJSON,
    LVMSConfigFromJSONTyped,
    LVMSConfigToJSON,
    LVMSConfigToJSONTyped,
} from './LVMSConfig.js';

/**
 * 
 * @export
 * @interface PluginsConfig
 */
export interface PluginsConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PluginsConfig
     */
    readonly $schema?: string;
    /**
     * Plugins to deploy
     * @type {Array<string>}
     * @memberof PluginsConfig
     */
    enabledPlugins?: Array<string> | null;
    /**
     * LVMS deployment configuration
     * @type {LVMSConfig}
     * @memberof PluginsConfig
     */
    lvmsDefaults?: LVMSConfig;
    /**
     * ODF deployment configuration
     * @type {ODFConfig}
     * @memberof PluginsConfig
     */
    odfDefaults?: ODFConfig;
}

/**
 * Check if a given object implements the PluginsConfig interface.
 */
export function instanceOfPluginsConfig(value: object): value is PluginsConfig {
    return true;
}

export function PluginsConfigFromJSON(json: any): PluginsConfig {
    return PluginsConfigFromJSONTyped(json, false);
}

export function PluginsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginsConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'enabledPlugins': json['enabled_plugins'] == null ? undefined : json['enabled_plugins'],
        'lvmsDefaults': json['lvmsDefaults'] == null ? undefined : LVMSConfigFromJSON(json['lvmsDefaults']),
        'odfDefaults': json['odfDefaults'] == null ? undefined : ODFConfigFromJSON(json['odfDefaults']),
    };
}

export function PluginsConfigToJSON(json: any): PluginsConfig {
    return PluginsConfigToJSONTyped(json, false);
}

export function PluginsConfigToJSONTyped(value?: Omit<PluginsConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled_plugins': value['enabledPlugins'],
        'lvmsDefaults': LVMSConfigToJSON(value['lvmsDefaults']),
        'odfDefaults': ODFConfigToJSON(value['odfDefaults']),
    };
}

