/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PreviewConfigOutputBody
 */
export interface PreviewConfigOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PreviewConfigOutputBody
     */
    readonly $schema?: string;
    /**
     * Rendered certificates.yaml content
     * @type {string}
     * @memberof PreviewConfigOutputBody
     */
    certificatesYaml: string;
    /**
     * Rendered cloud_infra.yaml content
     * @type {string}
     * @memberof PreviewConfigOutputBody
     */
    cloudInfraYaml: string;
    /**
     * Rendered global.yaml content
     * @type {string}
     * @memberof PreviewConfigOutputBody
     */
    globalYaml: string;
}

/**
 * Check if a given object implements the PreviewConfigOutputBody interface.
 */
export function instanceOfPreviewConfigOutputBody(value: object): value is PreviewConfigOutputBody {
    if (!('certificatesYaml' in value) || value['certificatesYaml'] === undefined) return false;
    if (!('cloudInfraYaml' in value) || value['cloudInfraYaml'] === undefined) return false;
    if (!('globalYaml' in value) || value['globalYaml'] === undefined) return false;
    return true;
}

export function PreviewConfigOutputBodyFromJSON(json: any): PreviewConfigOutputBody {
    return PreviewConfigOutputBodyFromJSONTyped(json, false);
}

export function PreviewConfigOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewConfigOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'certificatesYaml': json['certificatesYaml'],
        'cloudInfraYaml': json['cloudInfraYaml'],
        'globalYaml': json['globalYaml'],
    };
}

export function PreviewConfigOutputBodyToJSON(json: any): PreviewConfigOutputBody {
    return PreviewConfigOutputBodyToJSONTyped(json, false);
}

export function PreviewConfigOutputBodyToJSONTyped(value?: Omit<PreviewConfigOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certificatesYaml': value['certificatesYaml'],
        'cloudInfraYaml': value['cloudInfraYaml'],
        'globalYaml': value['globalYaml'],
    };
}

