/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { QuayBackendRGWConfiguration } from './QuayBackendRGWConfiguration.js';
import {
    QuayBackendRGWConfigurationFromJSON,
    QuayBackendRGWConfigurationFromJSONTyped,
    QuayBackendRGWConfigurationToJSON,
    QuayBackendRGWConfigurationToJSONTyped,
} from './QuayBackendRGWConfiguration.js';

/**
 * 
 * @export
 * @interface QuayConfig
 */
export interface QuayConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof QuayConfig
     */
    readonly $schema?: string;
    /**
     * oc-mirror log level
     * @type {string}
     * @memberof QuayConfig
     */
    ocMirrorLogLevel?: QuayConfigOcMirrorLogLevelEnum;
    /**
     * Quay image storage backend
     * @type {string}
     * @memberof QuayConfig
     */
    quayBackend: QuayConfigQuayBackendEnum;
    /**
     * RadosGW/S3 backend config (required when quayBackend is RadosGWStorage)
     * @type {QuayBackendRGWConfiguration}
     * @memberof QuayConfig
     */
    quayBackendRGWConfiguration?: QuayBackendRGWConfiguration;
    /**
     * Admin password for Quay registry
     * @type {string}
     * @memberof QuayConfig
     */
    quayPassword: string;
    /**
     * Admin username for Quay registry
     * @type {string}
     * @memberof QuayConfig
     */
    quayUser: string;
}


/**
 * @export
 */
export const QuayConfigOcMirrorLogLevelEnum = {
    Trace: 'trace',
    Debug: 'debug',
    Info: 'info',
    Error: 'error'
} as const;
export type QuayConfigOcMirrorLogLevelEnum = typeof QuayConfigOcMirrorLogLevelEnum[keyof typeof QuayConfigOcMirrorLogLevelEnum];

/**
 * @export
 */
export const QuayConfigQuayBackendEnum = {
    RadosGwStorage: 'RadosGWStorage',
    LocalStorage: 'LocalStorage'
} as const;
export type QuayConfigQuayBackendEnum = typeof QuayConfigQuayBackendEnum[keyof typeof QuayConfigQuayBackendEnum];


/**
 * Check if a given object implements the QuayConfig interface.
 */
export function instanceOfQuayConfig(value: object): value is QuayConfig {
    if (!('quayBackend' in value) || value['quayBackend'] === undefined) return false;
    if (!('quayPassword' in value) || value['quayPassword'] === undefined) return false;
    if (!('quayUser' in value) || value['quayUser'] === undefined) return false;
    return true;
}

export function QuayConfigFromJSON(json: any): QuayConfig {
    return QuayConfigFromJSONTyped(json, false);
}

export function QuayConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuayConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'ocMirrorLogLevel': json['ocMirrorLogLevel'] == null ? undefined : json['ocMirrorLogLevel'],
        'quayBackend': json['quayBackend'],
        'quayBackendRGWConfiguration': json['quayBackendRGWConfiguration'] == null ? undefined : QuayBackendRGWConfigurationFromJSON(json['quayBackendRGWConfiguration']),
        'quayPassword': json['quayPassword'],
        'quayUser': json['quayUser'],
    };
}

export function QuayConfigToJSON(json: any): QuayConfig {
    return QuayConfigToJSONTyped(json, false);
}

export function QuayConfigToJSONTyped(value?: Omit<QuayConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ocMirrorLogLevel': value['ocMirrorLogLevel'],
        'quayBackend': value['quayBackend'],
        'quayBackendRGWConfiguration': QuayBackendRGWConfigurationToJSON(value['quayBackendRGWConfiguration']),
        'quayPassword': value['quayPassword'],
        'quayUser': value['quayUser'],
    };
}

