/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QuayBackendRGWConfiguration
 */
export interface QuayBackendRGWConfiguration {
    /**
     * S3/RGW access key ID
     * @type {string}
     * @memberof QuayBackendRGWConfiguration
     */
    accessKey: string;
    /**
     * S3 bucket name for Quay image storage
     * @type {string}
     * @memberof QuayBackendRGWConfiguration
     */
    bucketName: string;
    /**
     * RadosGW/S3 endpoint hostname
     * @type {string}
     * @memberof QuayBackendRGWConfiguration
     */
    hostname: string;
    /**
     * Use HTTPS for backend storage (default: true)
     * @type {boolean}
     * @memberof QuayBackendRGWConfiguration
     */
    isSecure?: boolean;
    /**
     * Maximum multipart upload chunk size in MB
     * @type {number}
     * @memberof QuayBackendRGWConfiguration
     */
    maximumChunkSizeMb?: number;
    /**
     * Minimum multipart upload chunk size in MB
     * @type {number}
     * @memberof QuayBackendRGWConfiguration
     */
    minimumChunkSizeMb?: number;
    /**
     * Backend storage endpoint port (default: 443)
     * @type {number}
     * @memberof QuayBackendRGWConfiguration
     */
    port?: number;
    /**
     * S3/RGW secret access key
     * @type {string}
     * @memberof QuayBackendRGWConfiguration
     */
    secretKey: string;
    /**
     * Enable server-side assembly for multipart uploads
     * @type {boolean}
     * @memberof QuayBackendRGWConfiguration
     */
    serverSideAssembly?: boolean;
    /**
     * Object storage path prefix (must start with /)
     * @type {string}
     * @memberof QuayBackendRGWConfiguration
     */
    storagePath?: string;
}

/**
 * Check if a given object implements the QuayBackendRGWConfiguration interface.
 */
export function instanceOfQuayBackendRGWConfiguration(value: object): value is QuayBackendRGWConfiguration {
    if (!('accessKey' in value) || value['accessKey'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('secretKey' in value) || value['secretKey'] === undefined) return false;
    return true;
}

export function QuayBackendRGWConfigurationFromJSON(json: any): QuayBackendRGWConfiguration {
    return QuayBackendRGWConfigurationFromJSONTyped(json, false);
}

export function QuayBackendRGWConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuayBackendRGWConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKey': json['access_key'],
        'bucketName': json['bucket_name'],
        'hostname': json['hostname'],
        'isSecure': json['is_secure'] == null ? undefined : json['is_secure'],
        'maximumChunkSizeMb': json['maximum_chunk_size_mb'] == null ? undefined : json['maximum_chunk_size_mb'],
        'minimumChunkSizeMb': json['minimum_chunk_size_mb'] == null ? undefined : json['minimum_chunk_size_mb'],
        'port': json['port'] == null ? undefined : json['port'],
        'secretKey': json['secret_key'],
        'serverSideAssembly': json['server_side_assembly'] == null ? undefined : json['server_side_assembly'],
        'storagePath': json['storage_path'] == null ? undefined : json['storage_path'],
    };
}

export function QuayBackendRGWConfigurationToJSON(json: any): QuayBackendRGWConfiguration {
    return QuayBackendRGWConfigurationToJSONTyped(json, false);
}

export function QuayBackendRGWConfigurationToJSONTyped(value?: QuayBackendRGWConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key': value['accessKey'],
        'bucket_name': value['bucketName'],
        'hostname': value['hostname'],
        'is_secure': value['isSecure'],
        'maximum_chunk_size_mb': value['maximumChunkSizeMb'],
        'minimum_chunk_size_mb': value['minimumChunkSizeMb'],
        'port': value['port'],
        'secret_key': value['secretKey'],
        'server_side_assembly': value['serverSideAssembly'],
        'storage_path': value['storagePath'],
    };
}

