/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LVMSStorageConfig } from './LVMSStorageConfig.js';
import {
    LVMSStorageConfigFromJSON,
    LVMSStorageConfigFromJSONTyped,
    LVMSStorageConfigToJSON,
    LVMSStorageConfigToJSONTyped,
} from './LVMSStorageConfig.js';
import type { VASTVipPool } from './VASTVipPool.js';
import {
    VASTVipPoolFromJSON,
    VASTVipPoolFromJSONTyped,
    VASTVipPoolToJSON,
    VASTVipPoolToJSONTyped,
} from './VASTVipPool.js';

/**
 * 
 * @export
 * @interface StorageConfig
 */
export interface StorageConfig {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof StorageConfig
     */
    readonly $schema?: string;
    /**
     * Block storage backend
     * @type {string}
     * @memberof StorageConfig
     */
    blockStorageBackend: StorageConfigBlockStorageBackendEnum;
    /**
     * LVMS device selector configuration
     * @type {LVMSStorageConfig}
     * @memberof StorageConfig
     */
    lvmsConfig?: LVMSStorageConfig;
    /**
     * ODF external Ceph cluster config JSON (required when blockStorageBackend is odf)
     * @type {string}
     * @memberof StorageConfig
     */
    odfExternalConfig?: string;
    /**
     * Modern replacement for blockStorageBackend
     * @type {string}
     * @memberof StorageConfig
     */
    storagePlugin?: StorageConfigStoragePluginEnum;
    /**
     * VAST management API password
     * @type {string}
     * @memberof StorageConfig
     */
    vastAdminPassword?: string;
    /**
     * VAST management API username
     * @type {string}
     * @memberof StorageConfig
     */
    vastAdminUsername?: string;
    /**
     * VAST management endpoint URL (required when storage_plugin is vast-csi)
     * @type {string}
     * @memberof StorageConfig
     */
    vastEndpoint?: string;
    /**
     * VIP pool configuration for CSI traffic (required when storage_plugin is vast-csi)
     * @type {VASTVipPool}
     * @memberof StorageConfig
     */
    vastVipPool?: VASTVipPool;
}


/**
 * @export
 */
export const StorageConfigBlockStorageBackendEnum = {
    Lvms: 'lvms',
    Odf: 'odf',
    VastCsi: 'vast-csi'
} as const;
export type StorageConfigBlockStorageBackendEnum = typeof StorageConfigBlockStorageBackendEnum[keyof typeof StorageConfigBlockStorageBackendEnum];

/**
 * @export
 */
export const StorageConfigStoragePluginEnum = {
    Lvms: 'lvms',
    Odf: 'odf',
    VastCsi: 'vast-csi'
} as const;
export type StorageConfigStoragePluginEnum = typeof StorageConfigStoragePluginEnum[keyof typeof StorageConfigStoragePluginEnum];


/**
 * Check if a given object implements the StorageConfig interface.
 */
export function instanceOfStorageConfig(value: object): value is StorageConfig {
    if (!('blockStorageBackend' in value) || value['blockStorageBackend'] === undefined) return false;
    return true;
}

export function StorageConfigFromJSON(json: any): StorageConfig {
    return StorageConfigFromJSONTyped(json, false);
}

export function StorageConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageConfig {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'blockStorageBackend': json['blockStorageBackend'],
        'lvmsConfig': json['lvmsConfig'] == null ? undefined : LVMSStorageConfigFromJSON(json['lvmsConfig']),
        'odfExternalConfig': json['odfExternalConfig'] == null ? undefined : json['odfExternalConfig'],
        'storagePlugin': json['storage_plugin'] == null ? undefined : json['storage_plugin'],
        'vastAdminPassword': json['vastAdminPassword'] == null ? undefined : json['vastAdminPassword'],
        'vastAdminUsername': json['vastAdminUsername'] == null ? undefined : json['vastAdminUsername'],
        'vastEndpoint': json['vastEndpoint'] == null ? undefined : json['vastEndpoint'],
        'vastVipPool': json['vastVipPool'] == null ? undefined : VASTVipPoolFromJSON(json['vastVipPool']),
    };
}

export function StorageConfigToJSON(json: any): StorageConfig {
    return StorageConfigToJSONTyped(json, false);
}

export function StorageConfigToJSONTyped(value?: Omit<StorageConfig, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blockStorageBackend': value['blockStorageBackend'],
        'lvmsConfig': LVMSStorageConfigToJSON(value['lvmsConfig']),
        'odfExternalConfig': value['odfExternalConfig'],
        'storage_plugin': value['storagePlugin'],
        'vastAdminPassword': value['vastAdminPassword'],
        'vastAdminUsername': value['vastAdminUsername'],
        'vastEndpoint': value['vastEndpoint'],
        'vastVipPool': VASTVipPoolToJSON(value['vastVipPool']),
    };
}

