/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TaskEventsOutputBody
 */
export interface TaskEventsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof TaskEventsOutputBody
     */
    readonly $schema?: string;
    /**
     * Ansible Runner job events
     * @type {Array<object>}
     * @memberof TaskEventsOutputBody
     */
    events: Array<object>;
}

/**
 * Check if a given object implements the TaskEventsOutputBody interface.
 */
export function instanceOfTaskEventsOutputBody(value: object): value is TaskEventsOutputBody {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function TaskEventsOutputBodyFromJSON(json: any): TaskEventsOutputBody {
    return TaskEventsOutputBodyFromJSONTyped(json, false);
}

export function TaskEventsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskEventsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'events': json['events'],
    };
}

export function TaskEventsOutputBodyToJSON(json: any): TaskEventsOutputBody {
    return TaskEventsOutputBodyToJSONTyped(json, false);
}

export function TaskEventsOutputBodyToJSONTyped(value?: Omit<TaskEventsOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
    };
}

