/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TaskRun
 */
export interface TaskRun {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof TaskRun
     */
    readonly $schema?: string;
    /**
     * When the run completed
     * @type {Date}
     * @memberof TaskRun
     */
    endedAt?: Date;
    /**
     * Error message if failed
     * @type {string}
     * @memberof TaskRun
     */
    error?: string;
    /**
     * Process exit code
     * @type {number}
     * @memberof TaskRun
     */
    exitCode?: number;
    /**
     * Extra variables passed to ansible-runner
     * @type {{ [key: string]: string; }}
     * @memberof TaskRun
     */
    extraVars?: { [key: string]: string; };
    /**
     * Unique run identifier
     * @type {string}
     * @memberof TaskRun
     */
    id: string;
    /**
     * OS process ID of ansible-runner
     * @type {number}
     * @memberof TaskRun
     */
    pid?: number;
    /**
     * Playbook path relative to enclave directory
     * @type {string}
     * @memberof TaskRun
     */
    playbook: string;
    /**
     * When ansible-runner started
     * @type {Date}
     * @memberof TaskRun
     */
    startedAt: Date;
    /**
     * Current execution status
     * @type {string}
     * @memberof TaskRun
     */
    status: TaskRunStatusEnum;
    /**
     * Type of task
     * @type {string}
     * @memberof TaskRun
     */
    type: TaskRunTypeEnum;
}


/**
 * @export
 */
export const TaskRunStatusEnum = {
    Running: 'running',
    Successful: 'successful',
    Failed: 'failed',
    Canceled: 'canceled'
} as const;
export type TaskRunStatusEnum = typeof TaskRunStatusEnum[keyof typeof TaskRunStatusEnum];

/**
 * @export
 */
export const TaskRunTypeEnum = {
    Deploy: 'deploy',
    DeployPhase: 'deploy-phase',
    DeployPlugin: 'deploy-plugin',
    Validate: 'validate'
} as const;
export type TaskRunTypeEnum = typeof TaskRunTypeEnum[keyof typeof TaskRunTypeEnum];


/**
 * Check if a given object implements the TaskRun interface.
 */
export function instanceOfTaskRun(value: object): value is TaskRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('playbook' in value) || value['playbook'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TaskRunFromJSON(json: any): TaskRun {
    return TaskRunFromJSONTyped(json, false);
}

export function TaskRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRun {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'error': json['error'] == null ? undefined : json['error'],
        'exitCode': json['exitCode'] == null ? undefined : json['exitCode'],
        'extraVars': json['extraVars'] == null ? undefined : json['extraVars'],
        'id': json['id'],
        'pid': json['pid'] == null ? undefined : json['pid'],
        'playbook': json['playbook'],
        'startedAt': (new Date(json['startedAt'])),
        'status': json['status'],
        'type': json['type'],
    };
}

export function TaskRunToJSON(json: any): TaskRun {
    return TaskRunToJSONTyped(json, false);
}

export function TaskRunToJSONTyped(value?: Omit<TaskRun, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endedAt': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'error': value['error'],
        'exitCode': value['exitCode'],
        'extraVars': value['extraVars'],
        'id': value['id'],
        'pid': value['pid'],
        'playbook': value['playbook'],
        'startedAt': value['startedAt'].toISOString(),
        'status': value['status'],
        'type': value['type'],
    };
}

