/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TaskType } from './TaskType.js';
import {
    TaskTypeFromJSON,
    TaskTypeFromJSONTyped,
    TaskTypeToJSON,
    TaskTypeToJSONTyped,
} from './TaskType.js';
import type { TaskStatus } from './TaskStatus.js';
import {
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
    TaskStatusToJSONTyped,
} from './TaskStatus.js';

/**
 * 
 * @export
 * @interface TaskRun
 */
export interface TaskRun {
    /**
     * Unique run identifier
     * @type {string}
     * @memberof TaskRun
     */
    id: string;
    /**
     * 
     * @type {TaskType}
     * @memberof TaskRun
     */
    type: TaskType;
    /**
     * 
     * @type {TaskStatus}
     * @memberof TaskRun
     */
    status: TaskStatus;
    /**
     * Playbook path relative to enclave directory
     * @type {string}
     * @memberof TaskRun
     */
    playbook: string;
    /**
     * Extra variables passed to ansible-runner
     * @type {{ [key: string]: string; }}
     * @memberof TaskRun
     */
    extraVars?: { [key: string]: string; };
    /**
     * OS process ID of ansible-runner
     * @type {number}
     * @memberof TaskRun
     */
    pid?: number;
    /**
     * Process exit code
     * @type {number}
     * @memberof TaskRun
     */
    exitCode?: number | null;
    /**
     * When the run was created
     * @type {Date}
     * @memberof TaskRun
     */
    createdAt: Date;
    /**
     * When ansible-runner started
     * @type {Date}
     * @memberof TaskRun
     */
    startedAt?: Date | null;
    /**
     * When the run completed
     * @type {Date}
     * @memberof TaskRun
     */
    endedAt?: Date | null;
    /**
     * Error message if failed
     * @type {string}
     * @memberof TaskRun
     */
    error?: string;
}



/**
 * Check if a given object implements the TaskRun interface.
 */
export function instanceOfTaskRun(value: object): value is TaskRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('playbook' in value) || value['playbook'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TaskRunFromJSON(json: any): TaskRun {
    return TaskRunFromJSONTyped(json, false);
}

export function TaskRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': TaskTypeFromJSON(json['type']),
        'status': TaskStatusFromJSON(json['status']),
        'playbook': json['playbook'],
        'extraVars': json['extraVars'] == null ? undefined : json['extraVars'],
        'pid': json['pid'] == null ? undefined : json['pid'],
        'exitCode': json['exitCode'] == null ? undefined : json['exitCode'],
        'createdAt': (new Date(json['createdAt'])),
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function TaskRunToJSON(json: any): TaskRun {
    return TaskRunToJSONTyped(json, false);
}

export function TaskRunToJSONTyped(value?: TaskRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': TaskTypeToJSON(value['type']),
        'status': TaskStatusToJSON(value['status']),
        'playbook': value['playbook'],
        'extraVars': value['extraVars'],
        'pid': value['pid'],
        'exitCode': value['exitCode'],
        'createdAt': value['createdAt'].toISOString(),
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'endedAt': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'error': value['error'],
    };
}

