/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TrustManagerConfig
 */
export interface TrustManagerConfig {
    /**
     * CA certificate lifetime (e.g. 87600h for 10 years)
     * @type {string}
     * @memberof TrustManagerConfig
     */
    trustManagerCaIssuerDuration?: string;
    /**
     * How long before expiry to renew the CA (e.g. 8760h for 1 year)
     * @type {string}
     * @memberof TrustManagerConfig
     */
    trustManagerCaIssuerRenewBefore?: string;
}

/**
 * Check if a given object implements the TrustManagerConfig interface.
 */
export function instanceOfTrustManagerConfig(value: object): value is TrustManagerConfig {
    return true;
}

export function TrustManagerConfigFromJSON(json: any): TrustManagerConfig {
    return TrustManagerConfigFromJSONTyped(json, false);
}

export function TrustManagerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrustManagerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'trustManagerCaIssuerDuration': json['trust_manager_ca_issuer_duration'] == null ? undefined : json['trust_manager_ca_issuer_duration'],
        'trustManagerCaIssuerRenewBefore': json['trust_manager_ca_issuer_renew_before'] == null ? undefined : json['trust_manager_ca_issuer_renew_before'],
    };
}

export function TrustManagerConfigToJSON(json: any): TrustManagerConfig {
    return TrustManagerConfigToJSONTyped(json, false);
}

export function TrustManagerConfigToJSONTyped(value?: TrustManagerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trust_manager_ca_issuer_duration': value['trustManagerCaIssuerDuration'],
        'trust_manager_ca_issuer_renew_before': value['trustManagerCaIssuerRenewBefore'],
    };
}

