/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VASTIPRange } from './VASTIPRange.js';
import {
    VASTIPRangeFromJSON,
    VASTIPRangeFromJSONTyped,
    VASTIPRangeToJSON,
    VASTIPRangeToJSONTyped,
} from './VASTIPRange.js';

/**
 * 
 * @export
 * @interface VASTVipPool
 */
export interface VASTVipPool {
    /**
     * IP address ranges for VIP allocation
     * @type {Array<VASTIPRange>}
     * @memberof VASTVipPool
     */
    ipRanges: Array<VASTIPRange> | null;
    /**
     * Subnet prefix length
     * @type {number}
     * @memberof VASTVipPool
     */
    subnetCidr: number;
}

/**
 * Check if a given object implements the VASTVipPool interface.
 */
export function instanceOfVASTVipPool(value: object): value is VASTVipPool {
    if (!('ipRanges' in value) || value['ipRanges'] === undefined) return false;
    if (!('subnetCidr' in value) || value['subnetCidr'] === undefined) return false;
    return true;
}

export function VASTVipPoolFromJSON(json: any): VASTVipPool {
    return VASTVipPoolFromJSONTyped(json, false);
}

export function VASTVipPoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): VASTVipPool {
    if (json == null) {
        return json;
    }
    return {
        
        'ipRanges': (json['ip_ranges'] == null ? null : (json['ip_ranges'] as Array<any>).map(VASTIPRangeFromJSON)),
        'subnetCidr': json['subnet_cidr'],
    };
}

export function VASTVipPoolToJSON(json: any): VASTVipPool {
    return VASTVipPoolToJSONTyped(json, false);
}

export function VASTVipPoolToJSONTyped(value?: VASTVipPool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip_ranges': (value['ipRanges'] == null ? null : (value['ipRanges'] as Array<any>).map(VASTIPRangeToJSON)),
        'subnet_cidr': value['subnetCidr'],
    };
}

