/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VASTTier } from './VASTTier.js';
import {
    VASTTierFromJSON,
    VASTTierFromJSONTyped,
    VASTTierToJSON,
    VASTTierToJSONTyped,
} from './VASTTier.js';

/**
 * 
 * @export
 * @interface VASTConfig
 */
export interface VASTConfig {
    /**
     * Tenant name for infrastructure resources
     * @type {string}
     * @memberof VASTConfig
     */
    infraTenant?: string;
    /**
     * PVC size for Quay storage tier (e.g. 1000Gi)
     * @type {string}
     * @memberof VASTConfig
     */
    quayPvcSize?: string;
    /**
     * Root path on VAST cluster
     * @type {string}
     * @memberof VASTConfig
     */
    storagePath?: string;
    /**
     * Storage tiers to create on the VAST cluster
     * @type {Array<VASTTier>}
     * @memberof VASTConfig
     */
    tiers?: Array<VASTTier> | null;
    /**
     * VAST view policy ID
     * @type {number}
     * @memberof VASTConfig
     */
    viewPolicyId?: number;
}

/**
 * Check if a given object implements the VASTConfig interface.
 */
export function instanceOfVASTConfig(value: object): value is VASTConfig {
    return true;
}

export function VASTConfigFromJSON(json: any): VASTConfig {
    return VASTConfigFromJSONTyped(json, false);
}

export function VASTConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): VASTConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'infraTenant': json['infraTenant'] == null ? undefined : json['infraTenant'],
        'quayPvcSize': json['quayPvcSize'] == null ? undefined : json['quayPvcSize'],
        'storagePath': json['storagePath'] == null ? undefined : json['storagePath'],
        'tiers': json['tiers'] == null ? undefined : ((json['tiers'] as Array<any>).map(VASTTierFromJSON)),
        'viewPolicyId': json['viewPolicyId'] == null ? undefined : json['viewPolicyId'],
    };
}

export function VASTConfigToJSON(json: any): VASTConfig {
    return VASTConfigToJSONTyped(json, false);
}

export function VASTConfigToJSONTyped(value?: VASTConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'infraTenant': value['infraTenant'],
        'quayPvcSize': value['quayPvcSize'],
        'storagePath': value['storagePath'],
        'tiers': value['tiers'] == null ? undefined : ((value['tiers'] as Array<any>).map(VASTTierToJSON)),
        'viewPolicyId': value['viewPolicyId'],
    };
}

