/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VASTIPRange
 */
export interface VASTIPRange {
    /**
     * End IP address of the range
     * @type {string}
     * @memberof VASTIPRange
     */
    end: string;
    /**
     * Start IP address of the range
     * @type {string}
     * @memberof VASTIPRange
     */
    start: string;
}

/**
 * Check if a given object implements the VASTIPRange interface.
 */
export function instanceOfVASTIPRange(value: object): value is VASTIPRange {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function VASTIPRangeFromJSON(json: any): VASTIPRange {
    return VASTIPRangeFromJSONTyped(json, false);
}

export function VASTIPRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VASTIPRange {
    if (json == null) {
        return json;
    }
    return {
        
        'end': json['end'],
        'start': json['start'],
    };
}

export function VASTIPRangeToJSON(json: any): VASTIPRange {
    return VASTIPRangeToJSONTyped(json, false);
}

export function VASTIPRangeToJSONTyped(value?: VASTIPRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'],
        'start': value['start'],
    };
}

