/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VASTTier
 */
export interface VASTTier {
    /**
     * Storage tier name (becomes StorageClass suffix)
     * @type {string}
     * @memberof VASTTier
     */
    name: string;
    /**
     * Storage protocol
     * @type {string}
     * @memberof VASTTier
     */
    protocol: VASTTierProtocolEnum;
}


/**
 * @export
 */
export const VASTTierProtocolEnum = {
    Nfs: 'nfs',
    Block: 'block'
} as const;
export type VASTTierProtocolEnum = typeof VASTTierProtocolEnum[keyof typeof VASTTierProtocolEnum];


/**
 * Check if a given object implements the VASTTier interface.
 */
export function instanceOfVASTTier(value: object): value is VASTTier {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    return true;
}

export function VASTTierFromJSON(json: any): VASTTier {
    return VASTTierFromJSONTyped(json, false);
}

export function VASTTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): VASTTier {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'protocol': json['protocol'],
    };
}

export function VASTTierToJSON(json: any): VASTTier {
    return VASTTierToJSONTyped(json, false);
}

export function VASTTierToJSONTyped(value?: VASTTier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'protocol': value['protocol'],
    };
}

