/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VersionOutputBody
 */
export interface VersionOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof VersionOutputBody
     */
    readonly $schema?: string;
    /**
     * Enclave version or git hash
     * @type {string}
     * @memberof VersionOutputBody
     */
    enclaveVersion: string;
    /**
     * Enclave Wizard version or git hash
     * @type {string}
     * @memberof VersionOutputBody
     */
    wizardVersion: string;
}

/**
 * Check if a given object implements the VersionOutputBody interface.
 */
export function instanceOfVersionOutputBody(value: object): value is VersionOutputBody {
    if (!('enclaveVersion' in value) || value['enclaveVersion'] === undefined) return false;
    if (!('wizardVersion' in value) || value['wizardVersion'] === undefined) return false;
    return true;
}

export function VersionOutputBodyFromJSON(json: any): VersionOutputBody {
    return VersionOutputBodyFromJSONTyped(json, false);
}

export function VersionOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'enclaveVersion': json['enclaveVersion'],
        'wizardVersion': json['wizardVersion'],
    };
}

export function VersionOutputBodyToJSON(json: any): VersionOutputBody {
    return VersionOutputBodyToJSONTyped(json, false);
}

export function VersionOutputBodyToJSONTyped(value?: Omit<VersionOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enclaveVersion': value['enclaveVersion'],
        'wizardVersion': value['wizardVersion'],
    };
}

