// Code generated by schemagen. DO NOT EDIT.
package schema

type RhbkConfig struct {
	DBSize         *any  `yaml:"rhbk_db_size,omitempty" json:"rhbkDBSize,omitempty" doc:"PVC size for the PostgreSQL data volume."`
	DeployDatabase *bool `yaml:"rhbk_deploy_database,omitempty" json:"rhbkDeployDatabase,omitempty" doc:"Deploy a PostgreSQL StatefulSet alongside Keycloak."`
	Instances      *int  `yaml:"rhbk_instances,omitempty" json:"rhbkInstances,omitempty" doc:"Number of Keycloak replicas." minimum:"1"`
}
