// Code generated by schemagen. DO NOT EDIT.
package schema

type VastCsiConfig struct {
	VastCSIAdminPassword any             `yaml:"vastCSIAdminPassword" json:"vastCSIAdminPassword" doc:"VAST management API password."`
	VastCSIAdminUsername any             `yaml:"vastCSIAdminUsername" json:"vastCSIAdminUsername" doc:"VAST management API username."`
	VastCSIDefaults      *map[string]any `yaml:"vastCSIDefaults,omitempty" json:"vastCSIDefaults,omitempty" doc:"Overrides for VAST CSI driver defaults (see plugins/vast-csi/defaults.yaml)."`
	VastCSIEndpoint      any             `yaml:"vastCSIEndpoint" json:"vastCSIEndpoint" doc:"VAST management endpoint URL (e.g. https://vms.example.com)."`
	VastCSIVipPool       map[string]any  `yaml:"vastCSIVipPool" json:"vastCSIVipPool" doc:"VIP pool network configuration for CSI traffic."`
}
