// Code generated by schemagen. DO NOT EDIT.
package schema

type OdfConfig struct {
	OdfExternalConfig any `yaml:"odfExternalConfig" json:"odfExternalConfig" doc:"External Ceph cluster connection details JSON from ceph-external-cluster-details-exporter.py."`
}
