// Code generated by schemagen. DO NOT EDIT.
package schema

type LvmsConfig struct {
	LvmsConfig *map[string]any `yaml:"lvmsConfig,omitempty" json:"lvmsConfig,omitempty" doc:"LVMS storage configuration overrides for this deployment."`
}
