// Code generated by schemagen. DO NOT EDIT.
package schema

// PluginConfigTypes maps plugin names to constructors for their config types.
var PluginConfigTypes = map[string]func() any{
	"lvms":     func() any { return &LvmsConfig{} },
	"odf":      func() any { return &OdfConfig{} },
	"osac":     func() any { return &OsacConfig{} },
	"rhbk":     func() any { return &RhbkConfig{} },
	"vast-csi": func() any { return &VastCsiConfig{} },
}
