/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ChangePasswordInputBody,
  ChangePasswordOutputBody,
  ErrorModel,
  LoginInputBody,
  LoginOutputBody,
} from '../models/index.js';
import {
    ChangePasswordInputBodyFromJSON,
    ChangePasswordInputBodyToJSON,
    ChangePasswordOutputBodyFromJSON,
    ChangePasswordOutputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    LoginInputBodyFromJSON,
    LoginInputBodyToJSON,
    LoginOutputBodyFromJSON,
    LoginOutputBodyToJSON,
} from '../models/index.js';

export interface ChangePasswordRequest {
    changePasswordInputBody: Omit<ChangePasswordInputBody, '$schema'>;
}

export interface LoginRequest {
    loginInputBody: Omit<LoginInputBody, '$schema'>;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * 
     * @summary Change admin password
     * @param {ChangePasswordInputBody} changePasswordInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    changePasswordRaw(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangePasswordOutputBody>>;

    /**
     * Change admin password
     */
    changePassword(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangePasswordOutputBody>;

    /**
     * 
     * @summary Authenticate and get a bearer token
     * @param {LoginInputBody} loginInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOutputBody>>;

    /**
     * Authenticate and get a bearer token
     */
    login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOutputBody>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     * Change admin password
     */
    async changePasswordRaw(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangePasswordOutputBody>> {
        if (requestParameters['changePasswordInputBody'] == null) {
            throw new runtime.RequiredError(
                'changePasswordInputBody',
                'Required parameter "changePasswordInputBody" was null or undefined when calling changePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordInputBodyToJSON(requestParameters['changePasswordInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangePasswordOutputBodyFromJSON(jsonValue));
    }

    /**
     * Change admin password
     */
    async changePassword(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangePasswordOutputBody> {
        const response = await this.changePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Authenticate and get a bearer token
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOutputBody>> {
        if (requestParameters['loginInputBody'] == null) {
            throw new runtime.RequiredError(
                'loginInputBody',
                'Required parameter "loginInputBody" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginInputBodyToJSON(requestParameters['loginInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutputBodyFromJSON(jsonValue));
    }

    /**
     * Authenticate and get a bearer token
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOutputBody> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
