/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CertificatesConfig,
  ErrorModel,
} from '../models/index.js';
import {
    CertificatesConfigFromJSON,
    CertificatesConfigToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index.js';

export interface WriteConfigCertificatesRequest {
    certificatesConfig: Omit<CertificatesConfig, '$schema'>;
}

/**
 * CertificatesApi - interface
 * 
 * @export
 * @interface CertificatesApiInterface
 */
export interface CertificatesApiInterface {
    /**
     * 
     * @summary Load TLS certificates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiInterface
     */
    getConfigCertificatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CertificatesConfig>>;

    /**
     * Load TLS certificates
     */
    getConfigCertificates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CertificatesConfig>;

    /**
     * 
     * @summary Update TLS certificates
     * @param {CertificatesConfig} certificatesConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiInterface
     */
    writeConfigCertificatesRaw(requestParameters: WriteConfigCertificatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update TLS certificates
     */
    writeConfigCertificates(requestParameters: WriteConfigCertificatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class CertificatesApi extends runtime.BaseAPI implements CertificatesApiInterface {

    /**
     * Load TLS certificates
     */
    async getConfigCertificatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CertificatesConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/certificates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CertificatesConfigFromJSON(jsonValue));
    }

    /**
     * Load TLS certificates
     */
    async getConfigCertificates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CertificatesConfig> {
        const response = await this.getConfigCertificatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update TLS certificates
     */
    async writeConfigCertificatesRaw(requestParameters: WriteConfigCertificatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['certificatesConfig'] == null) {
            throw new runtime.RequiredError(
                'certificatesConfig',
                'Required parameter "certificatesConfig" was null or undefined when calling writeConfigCertificates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/certificates`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CertificatesConfigToJSON(requestParameters['certificatesConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update TLS certificates
     */
    async writeConfigCertificates(requestParameters: WriteConfigCertificatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigCertificatesRaw(requestParameters, initOverrides);
    }

}
