/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ClusterConfig,
  ErrorModel,
} from '../models/index.js';
import {
    ClusterConfigFromJSON,
    ClusterConfigToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index.js';

export interface WriteConfigClusterRequest {
    clusterConfig: Omit<ClusterConfig, '$schema'>;
}

/**
 * ClusterApi - interface
 * 
 * @export
 * @interface ClusterApiInterface
 */
export interface ClusterApiInterface {
    /**
     * 
     * @summary Load Management cluster install configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClusterApiInterface
     */
    getConfigClusterRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterConfig>>;

    /**
     * Load Management cluster install configuration
     */
    getConfigCluster(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterConfig>;

    /**
     * 
     * @summary Update Management cluster install configuration
     * @param {ClusterConfig} clusterConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClusterApiInterface
     */
    writeConfigClusterRaw(requestParameters: WriteConfigClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Management cluster install configuration
     */
    writeConfigCluster(requestParameters: WriteConfigClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ClusterApi extends runtime.BaseAPI implements ClusterApiInterface {

    /**
     * Load Management cluster install configuration
     */
    async getConfigClusterRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/cluster`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterConfigFromJSON(jsonValue));
    }

    /**
     * Load Management cluster install configuration
     */
    async getConfigCluster(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterConfig> {
        const response = await this.getConfigClusterRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Management cluster install configuration
     */
    async writeConfigClusterRaw(requestParameters: WriteConfigClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clusterConfig'] == null) {
            throw new runtime.RequiredError(
                'clusterConfig',
                'Required parameter "clusterConfig" was null or undefined when calling writeConfigCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/cluster`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ClusterConfigToJSON(requestParameters['clusterConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Management cluster install configuration
     */
    async writeConfigCluster(requestParameters: WriteConfigClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigClusterRaw(requestParameters, initOverrides);
    }

}
