/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  EnclaveConfig,
  ErrorModel,
  PreviewConfigOutputBody,
  ValidateConfigOutputBody,
} from '../models/index.js';
import {
    EnclaveConfigFromJSON,
    EnclaveConfigToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    PreviewConfigOutputBodyFromJSON,
    PreviewConfigOutputBodyToJSON,
    ValidateConfigOutputBodyFromJSON,
    ValidateConfigOutputBodyToJSON,
} from '../models/index.js';

export interface PreviewConfigRequest {
    enclaveConfig: Omit<EnclaveConfig, '$schema'>;
}

export interface ValidateConfigRequest {
    enclaveConfig: Omit<EnclaveConfig, '$schema'>;
}

export interface WriteConfigRequest {
    enclaveConfig: Omit<EnclaveConfig, '$schema'>;
}

/**
 * ConfigApi - interface
 * 
 * @export
 * @interface ConfigApiInterface
 */
export interface ConfigApiInterface {
    /**
     * Reads config/global.yaml, config/certificates.yaml, and config/cloud_infra.yaml from the Enclave directory and returns the merged configuration.
     * @summary Load existing configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApiInterface
     */
    getConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnclaveConfig>>;

    /**
     * Reads config/global.yaml, config/certificates.yaml, and config/cloud_infra.yaml from the Enclave directory and returns the merged configuration.
     * Load existing configuration
     */
    getConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnclaveConfig>;

    /**
     * Returns the rendered YAML content for each config file without writing to disk.
     * @summary Preview rendered YAML
     * @param {EnclaveConfig} enclaveConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApiInterface
     */
    previewConfigRaw(requestParameters: PreviewConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PreviewConfigOutputBody>>;

    /**
     * Returns the rendered YAML content for each config file without writing to disk.
     * Preview rendered YAML
     */
    previewConfig(requestParameters: PreviewConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PreviewConfigOutputBody>;

    /**
     * Validates the candidate configuration against Enclave JSON schemas and returns structured errors.
     * @summary Validate configuration
     * @param {EnclaveConfig} enclaveConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApiInterface
     */
    validateConfigRaw(requestParameters: ValidateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidateConfigOutputBody>>;

    /**
     * Validates the candidate configuration against Enclave JSON schemas and returns structured errors.
     * Validate configuration
     */
    validateConfig(requestParameters: ValidateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidateConfigOutputBody>;

    /**
     * Accepts wizard state, serializes to YAML, and writes to the Enclave config directory.
     * @summary Write configuration to disk
     * @param {EnclaveConfig} enclaveConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApiInterface
     */
    writeConfigRaw(requestParameters: WriteConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Accepts wizard state, serializes to YAML, and writes to the Enclave config directory.
     * Write configuration to disk
     */
    writeConfig(requestParameters: WriteConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ConfigApi extends runtime.BaseAPI implements ConfigApiInterface {

    /**
     * Reads config/global.yaml, config/certificates.yaml, and config/cloud_infra.yaml from the Enclave directory and returns the merged configuration.
     * Load existing configuration
     */
    async getConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnclaveConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnclaveConfigFromJSON(jsonValue));
    }

    /**
     * Reads config/global.yaml, config/certificates.yaml, and config/cloud_infra.yaml from the Enclave directory and returns the merged configuration.
     * Load existing configuration
     */
    async getConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnclaveConfig> {
        const response = await this.getConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the rendered YAML content for each config file without writing to disk.
     * Preview rendered YAML
     */
    async previewConfigRaw(requestParameters: PreviewConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PreviewConfigOutputBody>> {
        if (requestParameters['enclaveConfig'] == null) {
            throw new runtime.RequiredError(
                'enclaveConfig',
                'Required parameter "enclaveConfig" was null or undefined when calling previewConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/preview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnclaveConfigToJSON(requestParameters['enclaveConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreviewConfigOutputBodyFromJSON(jsonValue));
    }

    /**
     * Returns the rendered YAML content for each config file without writing to disk.
     * Preview rendered YAML
     */
    async previewConfig(requestParameters: PreviewConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PreviewConfigOutputBody> {
        const response = await this.previewConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validates the candidate configuration against Enclave JSON schemas and returns structured errors.
     * Validate configuration
     */
    async validateConfigRaw(requestParameters: ValidateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidateConfigOutputBody>> {
        if (requestParameters['enclaveConfig'] == null) {
            throw new runtime.RequiredError(
                'enclaveConfig',
                'Required parameter "enclaveConfig" was null or undefined when calling validateConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/validate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnclaveConfigToJSON(requestParameters['enclaveConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidateConfigOutputBodyFromJSON(jsonValue));
    }

    /**
     * Validates the candidate configuration against Enclave JSON schemas and returns structured errors.
     * Validate configuration
     */
    async validateConfig(requestParameters: ValidateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidateConfigOutputBody> {
        const response = await this.validateConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts wizard state, serializes to YAML, and writes to the Enclave config directory.
     * Write configuration to disk
     */
    async writeConfigRaw(requestParameters: WriteConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['enclaveConfig'] == null) {
            throw new runtime.RequiredError(
                'enclaveConfig',
                'Required parameter "enclaveConfig" was null or undefined when calling writeConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EnclaveConfigToJSON(requestParameters['enclaveConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Accepts wizard state, serializes to YAML, and writes to the Enclave config directory.
     * Write configuration to disk
     */
    async writeConfig(requestParameters: WriteConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigRaw(requestParameters, initOverrides);
    }

}
