/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Defaults,
  ErrorModel,
} from '../models/index.js';
import {
    DefaultsFromJSON,
    DefaultsToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index.js';

/**
 * DefaultsApi - interface
 * 
 * @export
 * @interface DefaultsApiInterface
 */
export interface DefaultsApiInterface {
    /**
     * Returns default values read from defaults/deployment.yaml and plugin definitions.
     * @summary Get default configuration values
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultsApiInterface
     */
    getDefaultsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Defaults>>;

    /**
     * Returns default values read from defaults/deployment.yaml and plugin definitions.
     * Get default configuration values
     */
    getDefaults(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Defaults>;

}

/**
 * 
 */
export class DefaultsApi extends runtime.BaseAPI implements DefaultsApiInterface {

    /**
     * Returns default values read from defaults/deployment.yaml and plugin definitions.
     * Get default configuration values
     */
    async getDefaultsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Defaults>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/defaults`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefaultsFromJSON(jsonValue));
    }

    /**
     * Returns default values read from defaults/deployment.yaml and plugin definitions.
     * Get default configuration values
     */
    async getDefaults(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Defaults> {
        const response = await this.getDefaultsRaw(initOverrides);
        return await response.value();
    }

}
