/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Deployment,
  DeploymentProgress,
  ErrorModel,
} from '../models/index.js';
import {
    DeploymentFromJSON,
    DeploymentToJSON,
    DeploymentProgressFromJSON,
    DeploymentProgressToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index.js';

export interface CancelDeploymentRequest {
    id: string;
}

export interface GetDeploymentByIdRequest {
    id: string;
}

export interface GetDeploymentProgressByIdRequest {
    id: string;
}

/**
 * DeploymentsApi - interface
 * 
 * @export
 * @interface DeploymentsApiInterface
 */
export interface DeploymentsApiInterface {
    /**
     * Cancels a running deployment.
     * @summary Cancel deployment
     * @param {string} id Deployment identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentsApiInterface
     */
    cancelDeploymentRaw(requestParameters: CancelDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Cancels a running deployment.
     * Cancel deployment
     */
    cancelDeployment(requestParameters: CancelDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns the most recent deployment. Use this for reconnection after page reload.
     * @summary Get current deployment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentsApiInterface
     */
    getCurrentDeploymentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>>;

    /**
     * Returns the most recent deployment. Use this for reconnection after page reload.
     * Get current deployment
     */
    getCurrentDeployment(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment>;

    /**
     * Returns the deployment state with phases for the given deployment ID.
     * @summary Get deployment by ID
     * @param {string} id Deployment identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentsApiInterface
     */
    getDeploymentByIdRaw(requestParameters: GetDeploymentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>>;

    /**
     * Returns the deployment state with phases for the given deployment ID.
     * Get deployment by ID
     */
    getDeploymentById(requestParameters: GetDeploymentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment>;

    /**
     * Returns live progress with completed task count, percentage, and current phase/task.
     * @summary Get deployment progress
     * @param {string} id Deployment identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentsApiInterface
     */
    getDeploymentProgressByIdRaw(requestParameters: GetDeploymentProgressByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentProgress>>;

    /**
     * Returns live progress with completed task count, percentage, and current phase/task.
     * Get deployment progress
     */
    getDeploymentProgressById(requestParameters: GetDeploymentProgressByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentProgress>;

    /**
     * Starts the full deployment chain (main playbook + addon plugins).
     * @summary Start deployment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentsApiInterface
     */
    startDeploymentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>>;

    /**
     * Starts the full deployment chain (main playbook + addon plugins).
     * Start deployment
     */
    startDeployment(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment>;

}

/**
 * 
 */
export class DeploymentsApi extends runtime.BaseAPI implements DeploymentsApiInterface {

    /**
     * Cancels a running deployment.
     * Cancel deployment
     */
    async cancelDeploymentRaw(requestParameters: CancelDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deployments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancels a running deployment.
     * Cancel deployment
     */
    async cancelDeployment(requestParameters: CancelDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelDeploymentRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the most recent deployment. Use this for reconnection after page reload.
     * Get current deployment
     */
    async getCurrentDeploymentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deployments/current`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentFromJSON(jsonValue));
    }

    /**
     * Returns the most recent deployment. Use this for reconnection after page reload.
     * Get current deployment
     */
    async getCurrentDeployment(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment> {
        const response = await this.getCurrentDeploymentRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the deployment state with phases for the given deployment ID.
     * Get deployment by ID
     */
    async getDeploymentByIdRaw(requestParameters: GetDeploymentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeploymentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deployments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentFromJSON(jsonValue));
    }

    /**
     * Returns the deployment state with phases for the given deployment ID.
     * Get deployment by ID
     */
    async getDeploymentById(requestParameters: GetDeploymentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment> {
        const response = await this.getDeploymentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns live progress with completed task count, percentage, and current phase/task.
     * Get deployment progress
     */
    async getDeploymentProgressByIdRaw(requestParameters: GetDeploymentProgressByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentProgress>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeploymentProgressById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deployments/{id}/progress`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentProgressFromJSON(jsonValue));
    }

    /**
     * Returns live progress with completed task count, percentage, and current phase/task.
     * Get deployment progress
     */
    async getDeploymentProgressById(requestParameters: GetDeploymentProgressByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentProgress> {
        const response = await this.getDeploymentProgressByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts the full deployment chain (main playbook + addon plugins).
     * Start deployment
     */
    async startDeploymentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deployments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentFromJSON(jsonValue));
    }

    /**
     * Starts the full deployment chain (main playbook + addon plugins).
     * Start deployment
     */
    async startDeployment(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment> {
        const response = await this.startDeploymentRaw(initOverrides);
        return await response.value();
    }

}
