/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  ExperiencesOutputBody,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    ExperiencesOutputBodyFromJSON,
    ExperiencesOutputBodyToJSON,
} from '../models/index.js';

/**
 * ExperiencesApi - interface
 * 
 * @export
 * @interface ExperiencesApiInterface
 */
export interface ExperiencesApiInterface {
    /**
     * Returns experience definitions loaded from the enclave directory.
     * @summary List available experiences
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExperiencesApiInterface
     */
    listExperiencesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExperiencesOutputBody>>;

    /**
     * Returns experience definitions loaded from the enclave directory.
     * List available experiences
     */
    listExperiences(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExperiencesOutputBody>;

}

/**
 * 
 */
export class ExperiencesApi extends runtime.BaseAPI implements ExperiencesApiInterface {

    /**
     * Returns experience definitions loaded from the enclave directory.
     * List available experiences
     */
    async listExperiencesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExperiencesOutputBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/experiences`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExperiencesOutputBodyFromJSON(jsonValue));
    }

    /**
     * Returns experience definitions loaded from the enclave directory.
     * List available experiences
     */
    async listExperiences(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExperiencesOutputBody> {
        const response = await this.listExperiencesRaw(initOverrides);
        return await response.value();
    }

}
