/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  CloudInfraConfig,
  ErrorModel,
} from '../models/index.js';
import {
    CloudInfraConfigFromJSON,
    CloudInfraConfigToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index.js';

export interface WriteConfigHostsRequest {
    cloudInfraConfig: Omit<CloudInfraConfig, '$schema'>;
}

/**
 * HostsApi - interface
 * 
 * @export
 * @interface HostsApiInterface
 */
export interface HostsApiInterface {
    /**
     * 
     * @summary Load Discovery hosts (cloud infrastructure)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostsApiInterface
     */
    getConfigHostsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CloudInfraConfig>>;

    /**
     * Load Discovery hosts (cloud infrastructure)
     */
    getConfigHosts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CloudInfraConfig>;

    /**
     * 
     * @summary Update Discovery hosts (cloud infrastructure)
     * @param {CloudInfraConfig} cloudInfraConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostsApiInterface
     */
    writeConfigHostsRaw(requestParameters: WriteConfigHostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Discovery hosts (cloud infrastructure)
     */
    writeConfigHosts(requestParameters: WriteConfigHostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class HostsApi extends runtime.BaseAPI implements HostsApiInterface {

    /**
     * Load Discovery hosts (cloud infrastructure)
     */
    async getConfigHostsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CloudInfraConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/hosts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CloudInfraConfigFromJSON(jsonValue));
    }

    /**
     * Load Discovery hosts (cloud infrastructure)
     */
    async getConfigHosts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CloudInfraConfig> {
        const response = await this.getConfigHostsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Discovery hosts (cloud infrastructure)
     */
    async writeConfigHostsRaw(requestParameters: WriteConfigHostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cloudInfraConfig'] == null) {
            throw new runtime.RequiredError(
                'cloudInfraConfig',
                'Required parameter "cloudInfraConfig" was null or undefined when calling writeConfigHosts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/hosts`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CloudInfraConfigToJSON(requestParameters['cloudInfraConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Discovery hosts (cloud infrastructure)
     */
    async writeConfigHosts(requestParameters: WriteConfigHostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigHostsRaw(requestParameters, initOverrides);
    }

}
