/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  LandingZoneConfig,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    LandingZoneConfigFromJSON,
    LandingZoneConfigToJSON,
} from '../models/index.js';

export interface WriteConfigLzRequest {
    landingZoneConfig: Omit<LandingZoneConfig, '$schema'>;
}

/**
 * LandingZoneApi - interface
 * 
 * @export
 * @interface LandingZoneApiInterface
 */
export interface LandingZoneApiInterface {
    /**
     * 
     * @summary Load Landing zone configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LandingZoneApiInterface
     */
    getConfigLzRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandingZoneConfig>>;

    /**
     * Load Landing zone configuration
     */
    getConfigLz(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandingZoneConfig>;

    /**
     * 
     * @summary Update Landing zone configuration
     * @param {LandingZoneConfig} landingZoneConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LandingZoneApiInterface
     */
    writeConfigLzRaw(requestParameters: WriteConfigLzRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Landing zone configuration
     */
    writeConfigLz(requestParameters: WriteConfigLzRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class LandingZoneApi extends runtime.BaseAPI implements LandingZoneApiInterface {

    /**
     * Load Landing zone configuration
     */
    async getConfigLzRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandingZoneConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/lz`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LandingZoneConfigFromJSON(jsonValue));
    }

    /**
     * Load Landing zone configuration
     */
    async getConfigLz(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandingZoneConfig> {
        const response = await this.getConfigLzRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Landing zone configuration
     */
    async writeConfigLzRaw(requestParameters: WriteConfigLzRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['landingZoneConfig'] == null) {
            throw new runtime.RequiredError(
                'landingZoneConfig',
                'Required parameter "landingZoneConfig" was null or undefined when calling writeConfigLz().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/lz`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LandingZoneConfigToJSON(requestParameters['landingZoneConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Landing zone configuration
     */
    async writeConfigLz(requestParameters: WriteConfigLzRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigLzRaw(requestParameters, initOverrides);
    }

}
