/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  NetworkConfig,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    NetworkConfigFromJSON,
    NetworkConfigToJSON,
} from '../models/index.js';

export interface WriteConfigNetworkRequest {
    networkConfig: Omit<NetworkConfig, '$schema'>;
}

/**
 * NetworkApi - interface
 * 
 * @export
 * @interface NetworkApiInterface
 */
export interface NetworkApiInterface {
    /**
     * 
     * @summary Load Host network configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NetworkApiInterface
     */
    getConfigNetworkRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkConfig>>;

    /**
     * Load Host network configuration
     */
    getConfigNetwork(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkConfig>;

    /**
     * 
     * @summary Update Host network configuration
     * @param {NetworkConfig} networkConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NetworkApiInterface
     */
    writeConfigNetworkRaw(requestParameters: WriteConfigNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Host network configuration
     */
    writeConfigNetwork(requestParameters: WriteConfigNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class NetworkApi extends runtime.BaseAPI implements NetworkApiInterface {

    /**
     * Load Host network configuration
     */
    async getConfigNetworkRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/network`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NetworkConfigFromJSON(jsonValue));
    }

    /**
     * Load Host network configuration
     */
    async getConfigNetwork(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkConfig> {
        const response = await this.getConfigNetworkRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Host network configuration
     */
    async writeConfigNetworkRaw(requestParameters: WriteConfigNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['networkConfig'] == null) {
            throw new runtime.RequiredError(
                'networkConfig',
                'Required parameter "networkConfig" was null or undefined when calling writeConfigNetwork().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/network`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NetworkConfigToJSON(requestParameters['networkConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Host network configuration
     */
    async writeConfigNetwork(requestParameters: WriteConfigNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigNetworkRaw(requestParameters, initOverrides);
    }

}
