/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  PluginValidateInputBody,
  PluginValidateOutputBody,
  PluginsConfig,
  PluginsOutputBody,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    PluginValidateInputBodyFromJSON,
    PluginValidateInputBodyToJSON,
    PluginValidateOutputBodyFromJSON,
    PluginValidateOutputBodyToJSON,
    PluginsConfigFromJSON,
    PluginsConfigToJSON,
    PluginsOutputBodyFromJSON,
    PluginsOutputBodyToJSON,
} from '../models/index.js';

export interface ValidatePluginCombinationRequest {
    pluginValidateInputBody: Omit<PluginValidateInputBody, '$schema'>;
}

export interface WriteConfigPluginsRequest {
    pluginsConfig: Omit<PluginsConfig, '$schema'>;
}

/**
 * PluginsApi - interface
 * 
 * @export
 * @interface PluginsApiInterface
 */
export interface PluginsApiInterface {
    /**
     * 
     * @summary Load Enabled plugins configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApiInterface
     */
    getConfigPluginsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginsConfig>>;

    /**
     * Load Enabled plugins configuration
     */
    getConfigPlugins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginsConfig>;

    /**
     * Returns all known plugins and their types.
     * @summary List available plugins
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApiInterface
     */
    listPluginsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginsOutputBody>>;

    /**
     * Returns all known plugins and their types.
     * List available plugins
     */
    listPlugins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginsOutputBody>;

    /**
     * Checks whether the given set of plugins forms a valid deployment combination.
     * @summary Validate plugin combination
     * @param {PluginValidateInputBody} pluginValidateInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApiInterface
     */
    validatePluginCombinationRaw(requestParameters: ValidatePluginCombinationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginValidateOutputBody>>;

    /**
     * Checks whether the given set of plugins forms a valid deployment combination.
     * Validate plugin combination
     */
    validatePluginCombination(requestParameters: ValidatePluginCombinationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginValidateOutputBody>;

    /**
     * 
     * @summary Update Enabled plugins configuration
     * @param {PluginsConfig} pluginsConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApiInterface
     */
    writeConfigPluginsRaw(requestParameters: WriteConfigPluginsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Enabled plugins configuration
     */
    writeConfigPlugins(requestParameters: WriteConfigPluginsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class PluginsApi extends runtime.BaseAPI implements PluginsApiInterface {

    /**
     * Load Enabled plugins configuration
     */
    async getConfigPluginsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginsConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/plugins`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginsConfigFromJSON(jsonValue));
    }

    /**
     * Load Enabled plugins configuration
     */
    async getConfigPlugins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginsConfig> {
        const response = await this.getConfigPluginsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all known plugins and their types.
     * List available plugins
     */
    async listPluginsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginsOutputBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/plugins`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginsOutputBodyFromJSON(jsonValue));
    }

    /**
     * Returns all known plugins and their types.
     * List available plugins
     */
    async listPlugins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginsOutputBody> {
        const response = await this.listPluginsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Checks whether the given set of plugins forms a valid deployment combination.
     * Validate plugin combination
     */
    async validatePluginCombinationRaw(requestParameters: ValidatePluginCombinationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginValidateOutputBody>> {
        if (requestParameters['pluginValidateInputBody'] == null) {
            throw new runtime.RequiredError(
                'pluginValidateInputBody',
                'Required parameter "pluginValidateInputBody" was null or undefined when calling validatePluginCombination().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/plugins/validate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PluginValidateInputBodyToJSON(requestParameters['pluginValidateInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginValidateOutputBodyFromJSON(jsonValue));
    }

    /**
     * Checks whether the given set of plugins forms a valid deployment combination.
     * Validate plugin combination
     */
    async validatePluginCombination(requestParameters: ValidatePluginCombinationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginValidateOutputBody> {
        const response = await this.validatePluginCombinationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Enabled plugins configuration
     */
    async writeConfigPluginsRaw(requestParameters: WriteConfigPluginsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pluginsConfig'] == null) {
            throw new runtime.RequiredError(
                'pluginsConfig',
                'Required parameter "pluginsConfig" was null or undefined when calling writeConfigPlugins().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/plugins`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PluginsConfigToJSON(requestParameters['pluginsConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Enabled plugins configuration
     */
    async writeConfigPlugins(requestParameters: WriteConfigPluginsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigPluginsRaw(requestParameters, initOverrides);
    }

}
