/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  QuayConfig,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    QuayConfigFromJSON,
    QuayConfigToJSON,
} from '../models/index.js';

export interface WriteConfigQuayRequest {
    quayConfig: Omit<QuayConfig, '$schema'>;
}

/**
 * QuayApi - interface
 * 
 * @export
 * @interface QuayApiInterface
 */
export interface QuayApiInterface {
    /**
     * 
     * @summary Load Quay registry configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuayApiInterface
     */
    getConfigQuayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuayConfig>>;

    /**
     * Load Quay registry configuration
     */
    getConfigQuay(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuayConfig>;

    /**
     * 
     * @summary Update Quay registry configuration
     * @param {QuayConfig} quayConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuayApiInterface
     */
    writeConfigQuayRaw(requestParameters: WriteConfigQuayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Quay registry configuration
     */
    writeConfigQuay(requestParameters: WriteConfigQuayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class QuayApi extends runtime.BaseAPI implements QuayApiInterface {

    /**
     * Load Quay registry configuration
     */
    async getConfigQuayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuayConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/quay`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuayConfigFromJSON(jsonValue));
    }

    /**
     * Load Quay registry configuration
     */
    async getConfigQuay(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuayConfig> {
        const response = await this.getConfigQuayRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Quay registry configuration
     */
    async writeConfigQuayRaw(requestParameters: WriteConfigQuayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['quayConfig'] == null) {
            throw new runtime.RequiredError(
                'quayConfig',
                'Required parameter "quayConfig" was null or undefined when calling writeConfigQuay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/quay`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: QuayConfigToJSON(requestParameters['quayConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Quay registry configuration
     */
    async writeConfigQuay(requestParameters: WriteConfigQuayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigQuayRaw(requestParameters, initOverrides);
    }

}
