/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  StorageConfig,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    StorageConfigFromJSON,
    StorageConfigToJSON,
} from '../models/index.js';

export interface WriteConfigStorageRequest {
    storageConfig: Omit<StorageConfig, '$schema'>;
}

/**
 * StorageApi - interface
 * 
 * @export
 * @interface StorageApiInterface
 */
export interface StorageApiInterface {
    /**
     * 
     * @summary Load Block storage configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageApiInterface
     */
    getConfigStorageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageConfig>>;

    /**
     * Load Block storage configuration
     */
    getConfigStorage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageConfig>;

    /**
     * 
     * @summary Update Block storage configuration
     * @param {StorageConfig} storageConfig 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StorageApiInterface
     */
    writeConfigStorageRaw(requestParameters: WriteConfigStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update Block storage configuration
     */
    writeConfigStorage(requestParameters: WriteConfigStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class StorageApi extends runtime.BaseAPI implements StorageApiInterface {

    /**
     * Load Block storage configuration
     */
    async getConfigStorageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config/storage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageConfigFromJSON(jsonValue));
    }

    /**
     * Load Block storage configuration
     */
    async getConfigStorage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageConfig> {
        const response = await this.getConfigStorageRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Block storage configuration
     */
    async writeConfigStorageRaw(requestParameters: WriteConfigStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['storageConfig'] == null) {
            throw new runtime.RequiredError(
                'storageConfig',
                'Required parameter "storageConfig" was null or undefined when calling writeConfigStorage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/config/storage`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StorageConfigToJSON(requestParameters['storageConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Block storage configuration
     */
    async writeConfigStorage(requestParameters: WriteConfigStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeConfigStorageRaw(requestParameters, initOverrides);
    }

}
