/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  GetTaskEventsOutputBody,
  ListTasksOutputBody,
  TaskRun,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetTaskEventsOutputBodyFromJSON,
    GetTaskEventsOutputBodyToJSON,
    ListTasksOutputBodyFromJSON,
    ListTasksOutputBodyToJSON,
    TaskRunFromJSON,
    TaskRunToJSON,
} from '../models/index.js';

export interface GetTaskRequest {
    id: string;
}

export interface GetTaskEventsRequest {
    id: string;
}

export interface GetTaskLogsRequest {
    id: string;
}

export interface StartDeployPhaseRequest {
    phase: number;
}

export interface StartDeployPluginRequest {
    name: string;
}

/**
 * TasksApi - interface
 * 
 * @export
 * @interface TasksApiInterface
 */
export interface TasksApiInterface {
    /**
     * Returns status and metadata for a specific run.
     * @summary Get task run details
     * @param {string} id Run identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    getTaskRaw(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>>;

    /**
     * Returns status and metadata for a specific run.
     * Get task run details
     */
    getTask(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun>;

    /**
     * Returns ansible-runner job events as a JSON array.
     * @summary Get task job events
     * @param {string} id Run identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    getTaskEventsRaw(requestParameters: GetTaskEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTaskEventsOutputBody>>;

    /**
     * Returns ansible-runner job events as a JSON array.
     * Get task job events
     */
    getTaskEvents(requestParameters: GetTaskEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTaskEventsOutputBody>;

    /**
     * Returns ansible-runner stdout as text/plain. Use the offset query parameter for incremental reads.
     * @summary Get task output logs
     * @param {string} id Run identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    getTaskLogsRaw(requestParameters: GetTaskLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Returns ansible-runner stdout as text/plain. Use the offset query parameter for incremental reads.
     * Get task output logs
     */
    getTaskLogs(requestParameters: GetTaskLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Returns all known task runs, most recent first.
     * @summary List all task runs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    listTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTasksOutputBody>>;

    /**
     * Returns all known task runs, most recent first.
     * List all task runs
     */
    listTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTasksOutputBody>;

    /**
     * Runs the main.yaml playbook (all 7 phases).
     * @summary Start full deployment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    startDeployRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>>;

    /**
     * Runs the main.yaml playbook (all 7 phases).
     * Start full deployment
     */
    startDeploy(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun>;

    /**
     * Runs a single deployment phase (1-7).
     * @summary Start a specific deployment phase
     * @param {number} phase Deployment phase number (1-7)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    startDeployPhaseRaw(requestParameters: StartDeployPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>>;

    /**
     * Runs a single deployment phase (1-7).
     * Start a specific deployment phase
     */
    startDeployPhase(requestParameters: StartDeployPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun>;

    /**
     * Runs the deploy-plugin.yaml playbook for the named plugin.
     * @summary Deploy a plugin
     * @param {string} name Plugin name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    startDeployPluginRaw(requestParameters: StartDeployPluginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>>;

    /**
     * Runs the deploy-plugin.yaml playbook for the named plugin.
     * Deploy a plugin
     */
    startDeployPlugin(requestParameters: StartDeployPluginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun>;

}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI implements TasksApiInterface {

    /**
     * Returns status and metadata for a specific run.
     * Get task run details
     */
    async getTaskRaw(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskRunFromJSON(jsonValue));
    }

    /**
     * Returns status and metadata for a specific run.
     * Get task run details
     */
    async getTask(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun> {
        const response = await this.getTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns ansible-runner job events as a JSON array.
     * Get task job events
     */
    async getTaskEventsRaw(requestParameters: GetTaskEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTaskEventsOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTaskEvents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/{id}/events`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTaskEventsOutputBodyFromJSON(jsonValue));
    }

    /**
     * Returns ansible-runner job events as a JSON array.
     * Get task job events
     */
    async getTaskEvents(requestParameters: GetTaskEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTaskEventsOutputBody> {
        const response = await this.getTaskEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns ansible-runner stdout as text/plain. Use the offset query parameter for incremental reads.
     * Get task output logs
     */
    async getTaskLogsRaw(requestParameters: GetTaskLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTaskLogs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/{id}/logs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns ansible-runner stdout as text/plain. Use the offset query parameter for incremental reads.
     * Get task output logs
     */
    async getTaskLogs(requestParameters: GetTaskLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getTaskLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all known task runs, most recent first.
     * List all task runs
     */
    async listTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTasksOutputBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTasksOutputBodyFromJSON(jsonValue));
    }

    /**
     * Returns all known task runs, most recent first.
     * List all task runs
     */
    async listTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTasksOutputBody> {
        const response = await this.listTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Runs the main.yaml playbook (all 7 phases).
     * Start full deployment
     */
    async startDeployRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/deploy`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskRunFromJSON(jsonValue));
    }

    /**
     * Runs the main.yaml playbook (all 7 phases).
     * Start full deployment
     */
    async startDeploy(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun> {
        const response = await this.startDeployRaw(initOverrides);
        return await response.value();
    }

    /**
     * Runs a single deployment phase (1-7).
     * Start a specific deployment phase
     */
    async startDeployPhaseRaw(requestParameters: StartDeployPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>> {
        if (requestParameters['phase'] == null) {
            throw new runtime.RequiredError(
                'phase',
                'Required parameter "phase" was null or undefined when calling startDeployPhase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/deploy/{phase}`;
        urlPath = urlPath.replace(`{${"phase"}}`, encodeURIComponent(String(requestParameters['phase'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskRunFromJSON(jsonValue));
    }

    /**
     * Runs a single deployment phase (1-7).
     * Start a specific deployment phase
     */
    async startDeployPhase(requestParameters: StartDeployPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun> {
        const response = await this.startDeployPhaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Runs the deploy-plugin.yaml playbook for the named plugin.
     * Deploy a plugin
     */
    async startDeployPluginRaw(requestParameters: StartDeployPluginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskRun>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling startDeployPlugin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/plugins/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskRunFromJSON(jsonValue));
    }

    /**
     * Runs the deploy-plugin.yaml playbook for the named plugin.
     * Deploy a plugin
     */
    async startDeployPlugin(requestParameters: StartDeployPluginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskRun> {
        const response = await this.startDeployPluginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
