/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorModel,
  VersionOutputBody,
} from '../models/index.js';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    VersionOutputBodyFromJSON,
    VersionOutputBodyToJSON,
} from '../models/index.js';

/**
 * VersionApi - interface
 * 
 * @export
 * @interface VersionApiInterface
 */
export interface VersionApiInterface {
    /**
     * 
     * @summary Get wizard and enclave versions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VersionApiInterface
     */
    getVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionOutputBody>>;

    /**
     * Get wizard and enclave versions
     */
    getVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionOutputBody>;

}

/**
 * 
 */
export class VersionApi extends runtime.BaseAPI implements VersionApiInterface {

    /**
     * Get wizard and enclave versions
     */
    async getVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionOutputBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/version`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get wizard and enclave versions
     */
    async getVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionOutputBody> {
        const response = await this.getVersionRaw(initOverrides);
        return await response.value();
    }

}
