FROM node:22-alpine AS build

RUN corepack enable

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/ .yarn/
COPY packages/ packages/
COPY apps/ apps/

RUN yarn install
RUN yarn build:all

FROM nginx:alpine

COPY --from=build /app/apps/wizard/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
