// Command schemagen reads JSON Schema (draft-07) YAML files from the enclave
// repo and generates Go structs with dual YAML/JSON tags, doc tags, and
// validation tags.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

// JSONSchema is a minimal representation of a JSON Schema draft-07 object.
type JSONSchema struct {
	Type        string                `yaml:"type"`
	Description string                `yaml:"description"`
	Properties  map[string]SchemaProperty `yaml:"properties"`
	Required    []string              `yaml:"required"`
}

// SchemaProperty represents a single property in a JSON Schema.
type SchemaProperty struct {
	Type        string   `yaml:"type"`
	Description string   `yaml:"description"`
	Minimum     *float64 `yaml:"minimum"`
	Maximum     *float64 `yaml:"maximum"`
	MinLength   *int     `yaml:"minLength"`
	MinItems    *int     `yaml:"minItems"`
	MaxItems    *int     `yaml:"maxItems"`
	Pattern     string   `yaml:"pattern"`
	Enum        []string `yaml:"enum"`
}

func main() {
	enclaveDir := flag.String("enclave-dir", "../enclave", "Path to enclave repo root")
	outputDir := flag.String("output", "internal/schema/", "Output directory for generated files")
	flag.Parse()

	plugins, err := discoverPlugins(*enclaveDir)
	if err != nil {
		log.Fatalf("discovering plugins: %v", err)
	}

	if len(plugins) == 0 {
		log.Fatalf("no plugin schemas found in %s/plugins/*/schemas/config.yaml", *enclaveDir)
	}

	if err := os.MkdirAll(*outputDir, 0755); err != nil {
		log.Fatalf("creating output dir: %v", err)
	}

	for _, p := range plugins {
		code, err := generatePluginFile(p.Name, p.Schema)
		if err != nil {
			log.Fatalf("generating plugin %s: %v", p.Name, err)
		}
		path := filepath.Join(*outputDir, "plugin_"+p.Name+".go")
		if err := os.WriteFile(path, code, 0644); err != nil {
			log.Fatalf("writing %s: %v", path, err)
		}
		fmt.Printf("generated %s\n", path)
	}

	registryCode, err := generateRegistryFile(plugins)
	if err != nil {
		log.Fatalf("generating registry: %v", err)
	}
	registryPath := filepath.Join(*outputDir, "registry.go")
	if err := os.WriteFile(registryPath, registryCode, 0644); err != nil {
		log.Fatalf("writing %s: %v", registryPath, err)
	}
	fmt.Printf("generated %s\n", registryPath)
}

// pluginInfo holds the name and parsed schema of a plugin.
type pluginInfo struct {
	Name   string
	Schema *JSONSchema
}

// discoverPlugins scans the enclave directory for plugin schemas.
func discoverPlugins(enclaveDir string) ([]pluginInfo, error) {
	pattern := filepath.Join(enclaveDir, "plugins", "*", "schemas", "config.yaml")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return nil, fmt.Errorf("globbing %s: %w", pattern, err)
	}

	var plugins []pluginInfo
	for _, path := range matches {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", path, err)
		}

		var schema JSONSchema
		if err := yaml.Unmarshal(data, &schema); err != nil {
			return nil, fmt.Errorf("parsing %s: %w", path, err)
		}

		// Extract plugin name from path: plugins/<name>/schemas/config.yaml
		parts := strings.Split(filepath.ToSlash(path), "/")
		var name string
		for i, p := range parts {
			if p == "plugins" && i+1 < len(parts) {
				name = parts[i+1]
				break
			}
		}
		if name == "" {
			return nil, fmt.Errorf("cannot extract plugin name from path %s", path)
		}

		plugins = append(plugins, pluginInfo{Name: name, Schema: &schema})
	}

	sort.Slice(plugins, func(i, j int) bool {
		return plugins[i].Name < plugins[j].Name
	})

	return plugins, nil
}

// generatePluginFile generates the Go source file for a single plugin.
func generatePluginFile(pluginName string, schema *JSONSchema) ([]byte, error) {
	structName := SnakeToPascal(pluginName) + "Config"

	requiredSet := make(map[string]bool)
	for _, r := range schema.Required {
		requiredSet[r] = true
	}

	// Sort properties for deterministic output
	propNames := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		propNames = append(propNames, name)
	}
	sort.Strings(propNames)

	var fields []string
	for _, propName := range propNames {
		prop := schema.Properties[propName]
		field := generateField(pluginName, propName, prop, requiredSet[propName])
		fields = append(fields, field)
	}

	src := fmt.Sprintf(`// Code generated by schemagen. DO NOT EDIT.
package schema

type %s struct {
%s
}
`, structName, strings.Join(fields, "\n"))

	return format.Source([]byte(src))
}

// generateField generates a single struct field line.
func generateField(pluginName, propName string, prop SchemaProperty, required bool) string {
	fieldName := SnakeToPascal(StripPrefix(propName, pluginName))
	goType := schemaTypeToGo(prop.Type)
	if !required {
		goType = "*" + goType
	}

	tags := buildTags(propName, prop, required)

	return fmt.Sprintf("\t%s %s %s", fieldName, goType, tags)
}

// buildTags constructs the struct tag string for a field.
func buildTags(propName string, prop SchemaProperty, required bool) string {
	var parts []string

	// YAML tag (preserves original snake_case)
	yamlTag := propName
	if !required {
		yamlTag += ",omitempty"
	}
	parts = append(parts, fmt.Sprintf(`yaml:"%s"`, yamlTag))

	// JSON tag (camelCase)
	jsonTag := SnakeToCamel(propName)
	if !required {
		jsonTag += ",omitempty"
	}
	parts = append(parts, fmt.Sprintf(`json:"%s"`, jsonTag))

	// Doc tag from description
	if prop.Description != "" {
		parts = append(parts, fmt.Sprintf(`doc:"%s"`, escapeTagValue(prop.Description)))
	}

	// Validation tags
	if prop.Minimum != nil {
		parts = append(parts, fmt.Sprintf(`minimum:"%s"`, formatNumber(*prop.Minimum)))
	}
	if prop.Maximum != nil {
		parts = append(parts, fmt.Sprintf(`maximum:"%s"`, formatNumber(*prop.Maximum)))
	}
	if prop.MinLength != nil {
		parts = append(parts, fmt.Sprintf(`minLength:"%d"`, *prop.MinLength))
	}
	if prop.MinItems != nil {
		parts = append(parts, fmt.Sprintf(`minItems:"%d"`, *prop.MinItems))
	}
	if prop.MaxItems != nil {
		parts = append(parts, fmt.Sprintf(`maxItems:"%d"`, *prop.MaxItems))
	}
	if prop.Pattern != "" {
		parts = append(parts, fmt.Sprintf(`pattern:"%s"`, escapeTagValue(prop.Pattern)))
	}
	if len(prop.Enum) > 0 {
		parts = append(parts, fmt.Sprintf(`enum:"%s"`, strings.Join(prop.Enum, ",")))
	}

	return "`" + strings.Join(parts, " ") + "`"
}

// generateRegistryFile generates the registry.go file mapping plugin names to
// config constructors.
func generateRegistryFile(plugins []pluginInfo) ([]byte, error) {
	var entries []string
	for _, p := range plugins {
		structName := SnakeToPascal(p.Name) + "Config"
		entries = append(entries, fmt.Sprintf("\t\t%q: func() any { return &%s{} },", p.Name, structName))
	}

	src := fmt.Sprintf(`// Code generated by schemagen. DO NOT EDIT.
package schema

// PluginConfigTypes maps plugin names to constructors for their config types.
var PluginConfigTypes = map[string]func() any{
%s
}
`, strings.Join(entries, "\n"))

	return format.Source([]byte(src))
}

// --- Name conversion utilities ---

// StripPrefix removes the plugin name prefix from a property name.
// Example: StripPrefix("rhbk_instances", "rhbk") -> "instances"
func StripPrefix(propName, prefix string) string {
	p := prefix + "_"
	if strings.HasPrefix(propName, p) {
		return propName[len(p):]
	}
	return propName
}

// SnakeToPascal converts snake_case or kebab-case to PascalCase.
func SnakeToPascal(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		// Handle common abbreviations
		upper := strings.ToUpper(p)
		if isAbbreviation(upper) {
			parts[i] = upper
			continue
		}
		parts[i] = string(unicode.ToUpper(rune(p[0]))) + p[1:]
	}
	return strings.Join(parts, "")
}

// SnakeToCamel converts snake_case to camelCase.
// Example: "rhbk_instances" -> "rhbkInstances"
func SnakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	if len(parts) == 0 {
		return s
	}
	// First segment stays lowercase
	result := parts[0]
	for _, p := range parts[1:] {
		if p == "" {
			continue
		}
		upper := strings.ToUpper(p)
		if isAbbreviation(upper) {
			result += upper
			continue
		}
		result += string(unicode.ToUpper(rune(p[0]))) + p[1:]
	}
	return result
}

// isAbbreviation checks if a string is a known abbreviation that should be
// all-caps in Go identifiers.
func isAbbreviation(s string) bool {
	abbreviations := map[string]bool{
		"ID":   true,
		"IP":   true,
		"URL":  true,
		"HTTP": true,
		"TLS":  true,
		"SSL":  true,
		"DNS":  true,
		"API":  true,
		"VIP":  true,
		"BMC":  true,
		"DB":   true,
		"PVC":  true,
		"NTP":  true,
	}
	return abbreviations[s]
}

// schemaTypeToGo maps JSON Schema types to Go types.
func schemaTypeToGo(schemaType string) string {
	switch schemaType {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]string"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

// formatNumber formats a float64 for struct tags, omitting the decimal point
// for integer values.
func formatNumber(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%g", f)
}

// escapeTagValue escapes characters that would break struct tag parsing.
func escapeTagValue(s string) string {
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
